In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kalil\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\kalil\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\kalil\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [3]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')
print(data.value_counts(['label']))

# Reduce the training set to speed up development. 
data = data.sample(frac=0.2, random_state=42)

# Modify for final system
# data = data.head(1000)
print(data.shape)
print(data.value_counts(['label']))
data.fillna("",inplace=True)

label
0        3386
1        2578
Name: count, dtype: int64
(1193, 2)
label
0        674
1        519
Name: count, dtype: int64

                                                   text  label
5713  MS -- Ijust spoke to Maggie and she can meet w...      0
810                                RELEASE IN PART B6Ok      0
2488                        Yes and we can certainly do      0
2960  Looks like there will be a three-way meeting i...      0
4680  Remain blessed in the name of the Lord.Yours i...      1
...                                                 ...    ...
5214    To serve as a guardian of this fund since I ...      1
925                             When is Steinberg call?      0
2985  My flight takes off at 8 so call before if you...      0
1886  My name is John paul, a member of Independent ...      1
1965  Dear Friend,  My name is Edward Garner; I am a...      1

[1193 rows x 2 columns]

### Let's divide the training and test set into two partitions

In [23]:
# Your code
import numpy as np
from sklearn.model_selection import train_test_split

X = data.drop(columns=["label"])
y = data["label"]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.3, random_state=42)

In [24]:
data

                                                   text  label
5713  MS -- Ijust spoke to Maggie and she can meet w...      0
810                                RELEASE IN PART B6Ok      0
2488                        Yes and we can certainly do      0
2960  Looks like there will be a three-way meeting i...      0
4680  Remain blessed in the name of the Lord.Yours i...      1
...                                                 ...    ...
5214    To serve as a guardian of this fund since I ...      1
925                             When is Steinberg call?      0
2985  My flight takes off at 8 so call before if you...      0
1886  My name is John paul, a member of Independent ...      1
1965  Dear Friend,  My name is Edward Garner; I am a...      1

[1193 rows x 2 columns]

## Data Preprocessing

In [5]:
from nltk.corpus import stopwords

In [6]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [25]:
# Your code
import re

def remove_jscss(text):

    text = re.sub(r"<script.*?</script>|<style.*?</style>", '', text, flags=re.DOTALL)
    text = re.sub(r"<!--.*?-->", '', text, flags=re.DOTALL)
    text = re.sub(r"<.*?>", '', text)
    return text

# testing = pd.read_csv("../data/kg_test.csv")
# print(f"\n\n {testing}.head(10)")
# testing["cleaned_text"] = testing["text"].apply(remove_jscss)
# print(f"\n\n {testing['cleaned_text'].head(10)}")

X_train["cleaned_text"] = X_train["text"].apply(remove_jscss)
X_val["cleaned_text"] = X_val["text"].apply(remove_jscss)

print(X_train["cleaned_text"].head())

2024    From Landler today middle of the piece -- not ...
932                   No - he's supposed to call me first
1926    I just landed from NY. The ppt looks good to m...
1421    1. The extension of pipeline network within Ni...
3622    Mills Cheryl D Thursday May 6 2010 3:18 PMFW: ...
Name: cleaned_text, dtype: str

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [26]:
# Your code
def remove_rest(text):
    text = re.sub(r"[^a-zA-Z0-9\s]", " ", text) # remove punctuation and special characters
    text = re.sub(r'\d', '', text) # remove numbers
    text = re.sub(r'\s+[a-zA-Z]\s+', ' ', text) # single character
    text = re.sub(r'^[a-zA-Z]\s+', ' ', text) # beginning of string
    text = re.sub(r'\s+', ' ', text) # multiple spaces
    text = re.sub(r'^b\s+', '', text) # remove 'b' at the beginning of the string but redundant because of  "remove single letter words" regex before, left here because it's asked
    text = text.lower()
    return text.strip().lower()


X_train["cleaned_text"] = X_train["cleaned_text"].apply(remove_rest)
X_val["cleaned_text"] = X_val["cleaned_text"].apply(remove_rest)

# remove_rest(remove_jscss(testing["text"]))




# new_clean = remove_rest(remove_jscss(testing))
print(X_train["cleaned_text"].head())

# df['clean'] = df['text'].apply(remove_jscss)
# df.head()

2024    from landler today middle of the piece not too...
932                       no he supposed to call me first
1926    just landed from ny the ppt looks good to me h...
1421    the extension of pipeline network within niger...
3622    mills cheryl thursday may pmfw luis alberto mo...
Name: cleaned_text, dtype: str

## Now let's work on removing stopwords
Remove the stopwords.

In [28]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words("english"))

def remove_stopwords(text):
    text = ' '.join([word for word in text.split() if word not in stop_words])
    return text

X_train["preprocessed_text"] = X_train["cleaned_text"].apply(remove_stopwords)
X_val["preprocessed_text"] = X_val["cleaned_text"].apply(remove_stopwords)

print(X_train["preprocessed_text"].head())

2024    landler today middle piece much israel also to...
932                                   supposed call first
1926    landed ny ppt looks good questions discuss tom...
1421    extension pipeline network within nigeria crud...
3622    mills cheryl thursday may pmfw luis alberto mo...
Name: preprocessed_text, dtype: str

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [29]:
# Your code
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    words = text.split()
    lemmatized = [lemmatizer.lemmatize(word, pos='v') for word in words]
    return ' '.join(lemmatized)

print(lemmatize_text("running ran runs"))

run run run

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [30]:
# Your code
from sklearn.feature_extraction.text import CountVectorizer

# testing.drop(columns=["text", "cleaned_text"], inplace=True)
vectorizer = CountVectorizer(min_df=5, max_df=0.9) # ignore words that appear in less than 5 documents or more than 90% of the documents such as Hash
vectorizer.fit(testing["remove_rest"])


print(f"\n\n {vectorizer.get_feature_names_out()[:10]}")

X = vectorizer.transform(testing["remove_rest"])

print(f"\n\n {X}")
print(f"\n\n {X.shape}")

 ['aa' 'aamsz' 'ab' 'abacha' 'abachas' 'abad' 'abandon' 'abandoned'
 'abandoning' 'abba']


 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 404024 stored elements and shape (5964, 9231)>
  Coords	Values
  (0, 49)	1
  (0, 59)	1
  (0, 75)	1
  (0, 547)	1
  (0, 733)	1
  (0, 803)	1
  (0, 852)	1
  (0, 875)	4
  (0, 885)	1
  (0, 1177)	1
  (0, 1244)	5
  (0, 1478)	1
  (0, 1539)	1
  (0, 1551)	1
  (0, 1659)	1
  (0, 1728)	1
  (0, 1797)	1
  (0, 1999)	1
  (0, 2154)	1
  (0, 2187)	2
  (0, 2244)	1
  (0, 2352)	1
  (0, 2439)	1
  (0, 2654)	1
  (0, 2876)	1
  :	:
  (5963, 7343)	1
  (5963, 7353)	1
  (5963, 7453)	1
  (5963, 7734)	1
  (5963, 7753)	2
  (5963, 7760)	1
  (5963, 7788)	1
  (5963, 7842)	1
  (5963, 8081)	1
  (5963, 8248)	1
  (5963, 8249)	3
  (5963, 8366)	1
  (5963, 8512)	1
  (5963, 8528)	1
  (5963, 8594)	1
  (5963, 8672)	1
  (5963, 8839)	1
  (5963, 8841)	1
  (5963, 8919)	1
  (5963, 8935)	1
  (5963, 8953)	1
  (5963, 8969)	1
  (5963, 9110)	1
  (5963, 9121)	1
  (5963, 9156)	2


 (5964, 9231)

## Extra features

In [33]:
data_train = X_train
data_val = X_val

In [34]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['preprocessed_text'].str.contains(money_simbol_list)*1
data_train['suspicious_words'] = data_train['preprocessed_text'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['preprocessed_text'].apply(lambda x: len(x)) 

data_val['money_mark'] = data_val['preprocessed_text'].str.contains(money_simbol_list)*1
data_val['suspicious_words'] = data_val['preprocessed_text'].str.contains(suspicious_words)*1
data_val['text_len'] = data_val['preprocessed_text'].apply(lambda x: len(x)) 

data_train.head()

,text,cleaned_text,preprocessed_text,money_mark,suspicious_words,text_len
2024,From Landler today middle of the piece -- not ...,from landler today middle of the piece not too...,landler today middle piece much israel also to...,0,0,569
932,No - he's supposed to call me first,no he supposed to call me first,supposed call first,0,0,19
1926,I just landed from NY. The ppt looks good to m...,just landed from ny the ppt looks good to me h...,landed ny ppt looks good questions discuss tom...,0,0,51
1421,1. The extension of pipeline network within Ni...,the extension of pipeline network within niger...,extension pipeline network within nigeria crud...,1,1,930
3622,Mills Cheryl D <MillsCD@state.gov>Thursday May...,mills cheryl thursday may pmfw luis alberto mo...,mills cheryl thursday may pmfw luis alberto mo...,0,0,50

## How would work the Bag of Words with Count Vectorizer concept?

In [40]:
# Your code

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(min_df=5, max_df=0.9) # ignore words that appear in less than 5 documents or more than 90% of the documents such as Hash
X_train_bow = vectorizer.fit_transform(data_train["preprocessed_text"])
X_val_bow = vectorizer.transform(data_val["preprocessed_text"])

print(vectorizer.get_feature_names_out()[:10])

print(X_train_bow.shape)
print(X_val_bow.shape)

print(X_train_bow[0])

['abacha' 'abandoned' 'abedin' 'abidjan' 'ability' 'able' 'abroad'
 'abroadwhere' 'absolute' 'absolutely']
(835, 2304)
(358, 2304)
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 36 stored elements and shape (1, 2304)>
  Coords	Values
  (0, 2094)	1
  (0, 1298)	1
  (0, 1545)	1
  (0, 1340)	1
  (0, 1092)	2
  (0, 84)	1
  (0, 2101)	1
  (0, 1094)	1
  (0, 1414)	1
  (0, 41)	3
  (0, 2162)	3
  (0, 1966)	3
  (0, 454)	1
  (0, 111)	1
  (0, 1808)	4
  (0, 1297)	1
  (0, 88)	1
  (0, 2106)	1
  (0, 1336)	1
  (0, 193)	1
  (0, 109)	1
  (0, 666)	1
  (0, 1093)	1
  (0, 901)	1
  (0, 1843)	1
  (0, 372)	1
  (0, 1963)	1
  (0, 556)	1
  (0, 1536)	1
  (0, 456)	1
  (0, 1869)	1
  (0, 1366)	1
  (0, 367)	1
  (0, 1018)	1
  (0, 90)	1
  (0, 363)	1

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [41]:
# Your code
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(min_df=5, max_df=0.9)
X_train_tfidf = vectorizer.fit_transform(data_train["preprocessed_text"])
X_val_tfidf = vectorizer.transform(data_val["preprocessed_text"])

print(vectorizer.get_feature_names_out()[:10])
print(X_train_tfidf.shape)
print(X_val_tfidf.shape)

print(X_train_tfidf[0])

['abacha' 'abandoned' 'abedin' 'abidjan' 'ability' 'able' 'abroad'
 'abroadwhere' 'absolute' 'absolutely']
(835, 2304)
(358, 2304)
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 36 stored elements and shape (1, 2304)>
  Coords	Values
  (0, 2094)	0.10224632380390691
  (0, 1298)	0.14502369819366784
  (0, 1545)	0.15732004655503978
  (0, 1340)	0.10026689058850352
  (0, 1092)	0.3073745950454854
  (0, 84)	0.07037891705593496
  (0, 2101)	0.11353495674190861
  (0, 1094)	0.11597287397143527
  (0, 1414)	0.134830085747089
  (0, 41)	0.3862782584557958
  (0, 2162)	0.22982743530050942
  (0, 1966)	0.2582547013166002
  (0, 454)	0.11683660384657629
  (0, 111)	0.134830085747089
  (0, 1808)	0.38511405154178224
  (0, 1297)	0.1536872975227427
  (0, 88)	0.13318078042713097
  (0, 2106)	0.14761663126091898
  (0, 1336)	0.06944071353474172
  (0, 193)	0.12268875322344153
  (0, 109)	0.15732004655503978
  (0, 666)	0.13318078042713097
  (0, 1093)	0.1615137475414816
  (0, 901)	0.08238139660488293
  (0, 1843)	0.12162174564602324
  (0, 372)	0.14761663126091898
  (0, 1963)	0.08024189413246688
  (0, 556)	0.10026689058850352
  (0, 1536)	0.14761663126091898
  (0, 456)	0.14047895742167693
  (0, 1869)	0.0946777449662549
  (0, 1366)	0.08213519396607818
  (0, 367)	0.1615137475414816
  (0, 1018)	0.10329280689456241
  (0, 90)	0.11683660384657629
  (0, 363)	0.14761663126091898

## And the Train a Classifier?

In [43]:
# Your code

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

clf = MultinomialNB()
clf.fit(X_train_tfidf, y_train)

y_pred = clf.predict(X_val_tfidf)
accuracy = accuracy_score(y_val, y_pred)
print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.9777

In [44]:
from sklearn.metrics import classification_report, confusion_matrix

print(classification_report(y_val, y_pred))
print(confusion_matrix(y_val, y_pred))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98       211
           1       0.99      0.96      0.97       147

    accuracy                           0.98       358
   macro avg       0.98      0.97      0.98       358
weighted avg       0.98      0.98      0.98       358

[[209   2]
 [  6 141]]

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [ ]:
# Your code