In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [3]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development.
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

In [4]:
data.head()

                                                text  label
0  DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                           Will do.      0
2  Nora--Cheryl has emailed dozens of memos about...      0
3  Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                fyi      0

### Let's divide the training and test set into two partitions

In [5]:
# Your code
from sklearn.model_selection import train_test_split

# Split into train (80%) and validation (20%)
data_train, data_val = train_test_split(data, test_size=0.2, random_state=42)

print(data_train.shape, data_val.shape)

(800, 2) (200, 2)

## Data Preprocessing

In [6]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [7]:
import string

from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [8]:
import re
from bs4 import BeautifulSoup, Comment

def clean_html_text(text):

    if pd.isna(text) or not isinstance(text, str):
        return ""

    # 1.
    text = re.sub(r'<script[^>]*>.*?</script>', '', text, flags=re.DOTALL|re.IGNORECASE)
    text = re.sub(r'<style[^>]*>.*?</style>', '', text, flags=re.DOTALL|re.IGNORECASE)

    # 2.
    text = re.sub(r'<!--.*?-->', '', text, flags=re.DOTALL)

    # 3.
    soup = BeautifulSoup(text, 'html.parser')
    text = soup.get_text(separator=' ')

    # 4.
    text = re.sub(r'[^\x00-\x7F]', '', text)
    text = re.sub(r'\s+', ' ', text)

    return text.strip()


data_train['cleaned_text'] = data_train['text'].apply(clean_html_text)
data_val['cleaned_text'] = data_val['text'].apply(clean_html_text)

/tmp/ipython-input-3966703324.py:17: MarkupResemblesLocatorWarning: The input passed in on this line looks more like a URL than HTML or XML.

If you meant to use Beautiful Soup to parse the web page found at a certain URL, then something has gone wrong. You should use an Python package like 'requests' to fetch the content behind the URL. Once you have the content as a string, you can feed that string into Beautiful Soup.

However, if you want to parse some data that happens to look like a URL, then nothing has gone wrong: you are using Beautiful Soup correctly, and this warning is spurious and can be filtered. To make this warning go away, run this code before calling the BeautifulSoup constructor:

    from bs4 import MarkupResemblesLocatorWarning
    import warnings

    warnings.filterwarnings("ignore", category=MarkupResemblesLocatorWarning)

  soup = BeautifulSoup(text, 'html.parser')

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters

- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [9]:
# Your code
def preprocess_text(text):

    if pd.isna(text) or not isinstance(text, str):
        return ""

    # Remove all special characters (keep only letters and spaces)
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Remove numbers
    text = re.sub(r'\d+', '', text)

    # Remove single characters from anywhere in the text
    text = re.sub(r'\b[a-zA-Z]\b', '', text)

    # Remove single characters from the start of the string
    text = re.sub(r'^\w\s+', '', text)

    # Substitute multiple spaces with single space
    text = re.sub(r'\s+', ' ', text)

    # Remove prefixed 'b' (common when converting bytes to string)
    text = re.sub(r'^b\s+', '', text)

    # Convert to lowercase
    text = text.lower()

    # Remove leading and trailing spaces
    text = text.strip()

    return text


data_train['preprocessed_text'] = data_train['cleaned_text'].apply(preprocess_text)
data_val['preprocessed_text'] = data_val['cleaned_text'].apply(preprocess_text)

## Now let's work on removing stopwords
Remove the stopwords.

In [10]:
# Your code

stopwords_set= set(stopwords.words("english"))

def remove_stopwords(text):
  filtered_words = []
  for word in text.split():
    if word not in stopwords_set:
      filtered_words.append(word)
  return " ".join(filtered_words)

data_train['preprocessed_text'] = data_train['preprocessed_text'].apply(remove_stopwords)
data_val['preprocessed_text'] = data_val['preprocessed_text'].apply(remove_stopwords)

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [11]:
import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [12]:
# Your code

from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize

lemmatizer = WordNetLemmatizer()

def text_lemmatized(text):
  tokenized_word = []
  for word in word_tokenize(text):
    tokenized_word.append(lemmatizer.lemmatize(word))
  return " ".join(tokenized_word)
data_train['preprocessed_text'] = data_train['preprocessed_text'].apply(text_lemmatized)
data_val['preprocessed_text'] = data_val['preprocessed_text'].apply(text_lemmatized)


X_train = data_train['preprocessed_text']
X_val = data_val['preprocessed_text']

y_train = data_train['label']
y_val = data_val['label']

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [13]:
# Your code

from collections import Counter
# Split Spam and Ham word
spam_words = " ".join(data_train[data_train['label']==1]['preprocessed_text']).split()
ham_words = " ".join(data_train[data_train['label']==0]['preprocessed_text']).split()

# Use Counter, to find the 10 most common words for each type
spam_count = Counter(spam_words)
ham_count = Counter(ham_words)

# Iteration to display the words and their frequency

top_10_spam = spam_count.most_common(10)
print("--- Top 10 Spam Word ---")
for word, times in top_10_spam:
  print(f"{word} is repreated : {times} times \n")

print("============================\n")
top_10_ham = ham_count.most_common(10)
print("--- Top 10 Ham Word ---")
for word, times in top_10_ham:
  print(f"{word} is repreated : {times} times \n")

--- Top 10 Spam Word ---
money is repreated : 800 times

account is repreated : 666 times

bank is repreated : 608 times

fund is repreated : 569 times

u is repreated : 446 times

business is repreated : 395 times

transaction is repreated : 354 times

country is repreated : 342 times

transfer is repreated : 332 times

company is repreated : 321 times

============================

--- Top 10 Ham Word ---
u is repreated : 99 times

state is repreated : 92 times

would is repreated : 92 times

pm is repreated : 89 times

president is repreated : 84 times

percent is repreated : 76 times

call is repreated : 73 times

secretary is repreated : 71 times

time is repreated : 70 times

mr is repreated : 70 times

## Extra features

In [14]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['preprocessed_text'].str.contains(money_simbol_list)*1
data_train['suspicious_words'] = data_train['preprocessed_text'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['preprocessed_text'].apply(lambda x: len(x))

data_val['money_mark'] = data_val['preprocessed_text'].str.contains(money_simbol_list)*1
data_val['suspicious_words'] = data_val['preprocessed_text'].str.contains(suspicious_words)*1
data_val['text_len'] = data_val['preprocessed_text'].apply(lambda x: len(x))

data_train.head()

,text,label,cleaned_text,preprocessed_text,money_mark,suspicious_words,text_len
29,"----------- REGARDS, MR NELSON SMITH.KINDLY RE...",1,"----------- REGARDS, MR NELSON SMITH.KINDLY RE...",regard mr nelson smithkindly reply private ema...,0,0,75
535,I have not been able to reach oscar this am. W...,0,I have not been able to reach oscar this am. W...,able reach oscar supposed send pdb receive,0,0,42
695,; Huma Abedin B6I'm checking with Pat on the 5...,0,; Huma Abedin B6I'm checking with Pat on the 5...,huma abedin bim checking pat work jack jake re...,0,0,79
557,I can have it announced here on Monday - can't...,0,I can have it announced here on Monday - can't...,announced monday cant today,0,0,27
836,BANK OF AFRICAAGENCE SAN PEDRO14 BP 1210 S...,1,BANK OF AFRICAAGENCE SAN PEDRO14 BP 1210 San P...,bank africaagence san pedro bp san pedro cote ...,1,1,1067

## How would work the Bag of Words with Count Vectorizer concept?

In [15]:
# And now the bag of words

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X_train_bwords = vectorizer.fit_transform(X_train)
X_val_bwords = vectorizer.transform(X_val)

print("Train  CountVectorizer shape:", X_train_bwords.shape)
print("Validation CountVectorizer shape:", X_val_bwords.shape)

Train  CountVectorizer shape: (800, 16668)
Validation CountVectorizer shape: (200, 16668)

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [16]:
# Your code

# Load the vectorizer

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

# Vectorize the dataset

X_train_tfidf = tfidf.fit_transform(X_train)
X_val_tfidf = tfidf.transform(X_val)

print("Train TF-IDF shape:", X_train_tfidf.shape)
print("Validation TF-IDF shape:", X_val_tfidf.shape)

Train TF-IDF shape: (800, 16668)
Validation TF-IDF shape: (200, 16668)

## And the Train a Classifier?

In [17]:
# Your code

# Import the MultinomialNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Build the model
nb_model = MultinomialNB()

# Fit the model
nb_model.fit(X_train_tfidf, y_train)

# Make predictions
y_pred = nb_model.predict(X_val_tfidf)

# Evaluate the model
print("Accuracy:", accuracy_score(y_val, y_pred))

print(classification_report(y_val, y_pred))

Accuracy: 0.94
              precision    recall  f1-score   support

           0       1.00      0.90      0.95       125
           1       0.86      1.00      0.93        75

    accuracy                           0.94       200
   macro avg       0.93      0.95      0.94       200
weighted avg       0.95      0.94      0.94       200

#Analysis


The classifier achieved an overall accuracy of 94%, which indicates strong performance on the validation set. Looking at the detailed metrics:

*   Class 0 (Ham): Precision is 100%, meaning all emails predicted as Ham were correct. Recall is 90%, so 10% of actual Ham emails were misclassified as Spam. F1-score is 95%, showing a good balance between precision and recall.

*   Class 1 (Spam): Precision is 86%, and recall is 100%, meaning all Spam emails were correctly identified, though some Ham emails were incorrectly labeled as Spam. F1-score is 93%.

> Support shows there are 125 Ham and 75 Spam emails in the validation set.

Although the results are good, there could be some overfitting, especially given the small size of the Dataset (with 1000 samples).

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

# Bag of words only

In [19]:
# Your code



from sklearn.feature_extraction.text import CountVectorizer

# Initialize CountVectorizer
vectorizer_bow = CountVectorizer()

# Fit on training text
X_train_bow = vectorizer_bow.fit_transform(X_train)
X_val_bow   = vectorizer_bow.transform(X_val)

print("BOW shape - train:", X_train_bow.shape, "val:", X_val_bow.shape)

BOW shape - train: (800, 16668) val: (200, 16668)

In [20]:
# Train MultinomialNB using Bag of Words

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

clf_bow = MultinomialNB()
clf_bow.fit(X_train_bow, y_train)

y_pred_bow = clf_bow.predict(X_val_bow)

print("Accuracy (BOW):", accuracy_score(y_val, y_pred_bow))
print(classification_report(y_val, y_pred_bow))

# Top 10 Words for Spam and Ham
import numpy as np

feature_names = vectorizer_bow.get_feature_names_out()

# Probabilities for each class
class0_prob = clf_bow.feature_log_prob_[0]  # Ham
class1_prob = clf_bow.feature_log_prob_[1]  # Spam

# Top 10 words for Spam
top_spam_indices = np.argsort(class1_prob)[-10:]
top_spam_words = feature_names[top_spam_indices]
print("Top 10 Spam words:", top_spam_words)

# Top 10 words for Ham
top_ham_indices = np.argsort(class0_prob)[-10:]
top_ham_words = feature_names[top_ham_indices]
print("Top 10 Ham words:", top_ham_words)

Accuracy (BOW): 0.935
              precision    recall  f1-score   support

           0       0.99      0.90      0.95       125
           1       0.86      0.99      0.92        75

    accuracy                           0.94       200
   macro avg       0.93      0.95      0.93       200
weighted avg       0.94      0.94      0.94       200

Top 10 Spam words: ['million' 'company' 'transfer' 'country' 'transaction' 'business' 'fund'
 'bank' 'account' 'money']
Top 10 Ham words: ['work' 'mr' 'time' 'secretary' 'call' 'percent' 'president' 'pm' 'would'
 'state']

# TF-IDF only

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer_tfidf = TfidfVectorizer()
X_train_tfidf = vectorizer_tfidf.fit_transform(X_train)
X_val_tfidf   = vectorizer_tfidf.transform(X_val)

clf_tfidf = MultinomialNB()
clf_tfidf.fit(X_train_tfidf, y_train)

y_pred_tfidf = clf_tfidf.predict(X_val_tfidf)
print("Accuracy (TF-IDF):", accuracy_score(y_val, y_pred_tfidf))
print(classification_report(y_val, y_pred_tfidf))

Accuracy (TF-IDF): 0.94
              precision    recall  f1-score   support

           0       1.00      0.90      0.95       125
           1       0.86      1.00      0.93        75

    accuracy                           0.94       200
   macro avg       0.93      0.95      0.94       200
weighted avg       0.95      0.94      0.94       200

# Add extra featuress

In [23]:
from scipy.sparse import hstack

extra_train_np = data_train[['money_mark','suspicious_words','text_len']].to_numpy()
extra_val_np   = data_val[['money_mark','suspicious_words','text_len']].to_numpy()

X_train_bow_extra = hstack([X_train_bow, extra_train_np])
X_val_bow_extra   = hstack([X_val_bow, extra_val_np])

clf_bow_extra = MultinomialNB()
clf_bow_extra.fit(X_train_bow_extra, y_train)

y_pred_bow_extra = clf_bow_extra.predict(X_val_bow_extra)
print("Accuracy (BOW + extra):", accuracy_score(y_val, y_pred_bow_extra))

Accuracy (BOW + extra): 0.865