In [5]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [7]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

                                                  text  label
0    DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                             Will do.      0
2    Nora--Cheryl has emailed dozens of memos about...      0
3    Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                  fyi      0
..                                                 ...    ...
995  So what's the latest? It sounds contradictory ...      0
996  TRANSFER OF 36,759,000.00 MILLION POUNDS TO YO...      1
997  Barb I will call to explain. Are you back in t...      0
998    Yang on travelNot free tonite.May work tomorrow      0
999  sbwhoeopSunday February 21 2010 7:42 PMHShaunH...      0

[1000 rows x 2 columns]

### Let's divide the training and test set into two partitions

In [8]:
# Your code
from sklearn.model_selection import train_test_split
data_train, data_val = train_test_split(data, test_size=0.2, random_state=42,stratify=data["label"])
print(data_train.shape)
print(data_val.shape)
display(data_train.head())

(800, 2)
(200, 2)

                                                  text  label
442  Dear=2C Good day hope fine=2Cdear am writting ...      1
962  FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...      1
971                                           Will do.      0
190  FROM THE DESK OF DR.ADAMU  ISMALERAUDITING AND...      1
551  Dear Friend, My name is LOI C.ESTRADA,The wife...      1

## Data Preprocessing

In [9]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [10]:
# Your code
import re

def remove_html(text):
    text = re.sub(r"<script.*?>.*?</script>", " ", text, flags=re.DOTALL)
    text = re.sub(r"<style.*?>.*?</style>", " ", text, flags=re.DOTALL)
    text = re.sub(r"<!--.*?-->", " ", text, flags=re.DOTALL)
    text = re.sub(r"<.*?>", " ", text)
    return text

data_train["clean_text"] = data_train["text"].apply(remove_html)
data_val["clean_text"] = data_val["text"].apply(remove_html)

display(data_train[["text", "clean_text"]].head())

,text,clean_text
442,Dear=2C Good day hope fine=2Cdear am writting ...,Dear=2C Good day hope fine=2Cdear am writting ...
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...
971,Will do.,Will do.
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...","Dear Friend, My name is LOI C.ESTRADA,The wife..."

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [11]:
# Your code
def clean_text(text):
    text = re.sub(r"\W", " ", text)          # Remove special characters
    text = re.sub(r"\d+", " ", text)        # Remove numbers
    text = re.sub(r"\s+[a-zA-Z]\s+", " ", text)  # Remove single characters
    text = re.sub(r"^[a-zA-Z]\s+", " ", text)   # Remove single character at start
    text = re.sub(r"\s+", " ", text)       # Multiple spaces into one
    text = re.sub(r"^b\s+", "", text)      # Remove prefixed b
    text = text.lower()                     # Lowercase
    return text.strip()

data_train["clean_text"] = data_train["clean_text"].apply(clean_text)
data_val["clean_text"] = data_val["clean_text"].apply(clean_text)

display(data_train[["text", "clean_text"]].head())

,text,clean_text
442,Dear=2C Good day hope fine=2Cdear am writting ...,dear good day hope fine cdear am writting this...
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,from mr henry kaborethe chief auditor incharge...
971,Will do.,will do
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,from the desk of dr adamu ismalerauditing and ...
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...",dear friend my name is loi estrada the wife of...

## Now let's work on removing stopwords
Remove the stopwords.

In [12]:
# Your code
import nltk
nltk.download("stopwords")

from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

def remove_stopwords(text):
    words = text.split()
    words = [word for word in words if word not in stop_words]
    return " ".join(words)

data_train["clean_text"] = data_train["clean_text"].apply(remove_stopwords)
data_val["clean_text"] = data_val["clean_text"].apply(remove_stopwords)

display(data_train[["text", "clean_text"]].head())

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/gregori/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,text,clean_text
442,Dear=2C Good day hope fine=2Cdear am writting ...,dear good day hope fine cdear writting mail du...
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,mr henry kaborethe chief auditor inchargeforei...
971,Will do.,
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,desk dr adamu ismalerauditing accounting manag...
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...",dear friend name loi estrada wife mr josephest...

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [13]:
# Your code
import nltk
nltk.download("wordnet")
nltk.download("omw-1.4")

from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    words = text.split()
    words = [lemmatizer.lemmatize(word) for word in words]
    return " ".join(words)

data_train["preprocessed_text"] = data_train["clean_text"].apply(lemmatize_text)
data_val["preprocessed_text"] = data_val["clean_text"].apply(lemmatize_text)

display(data_train[["text", "preprocessed_text"]].head())

[nltk_data] Downloading package wordnet to /home/gregori/nltk_data...
[nltk_data] Downloading package omw-1.4 to /home/gregori/nltk_data...

,text,preprocessed_text
442,Dear=2C Good day hope fine=2Cdear am writting ...,dear good day hope fine cdear writting mail du...
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,mr henry kaborethe chief auditor inchargeforei...
971,Will do.,
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,desk dr adamu ismalerauditing accounting manag...
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...",dear friend name loi estrada wife mr josephest...

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [17]:
# Your code
from collections import Counter

ham_text = " ".join(data_train[data_train["label"] == 0]["preprocessed_text"])
spam_text = " ".join(data_train[data_train["label"] == 1]["preprocessed_text"])

ham_words = Counter(ham_text.split())
spam_words = Counter(spam_text.split())

top_ham = pd.DataFrame(ham_words.most_common(10), columns=["word", "count"])
top_spam = pd.DataFrame(spam_words.most_common(10), columns=["word", "count"])

print("Top 10 HAM words:")
display(top_ham)

print("Top 10 SPAM words:")
display(top_spam)

Top 10 HAM words:

        word  count
0          â    205
1      state     97
2  president     95
3      would     92
4         mr     90
5          ã     87
6      obama     80
7    percent     80
8       call     77
9       work     72

Top 10 SPAM words:

          word  count
0        money    761
1      account    674
2            u    631
3         bank    615
4         fund    600
5            e    523
6  transaction    435
7     business    412
8      country    401
9         nbsp    387

## Extra features

In [15]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['preprocessed_text'].str.contains(money_simbol_list)*1
data_train['suspicious_words'] = data_train['preprocessed_text'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['preprocessed_text'].apply(lambda x: len(x)) 

data_val['money_mark'] = data_val['preprocessed_text'].str.contains(money_simbol_list)*1
data_val['suspicious_words'] = data_val['preprocessed_text'].str.contains(suspicious_words)*1
data_val['text_len'] = data_val['preprocessed_text'].apply(lambda x: len(x)) 

data_train.head()

,text,label,clean_text,preprocessed_text,money_mark,suspicious_words,text_len
442,Dear=2C Good day hope fine=2Cdear am writting ...,1,dear good day hope fine cdear writting mail du...,dear good day hope fine cdear writting mail du...,1,1,1002
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,1,mr henry kaborethe chief auditor inchargeforei...,mr henry kaborethe chief auditor inchargeforei...,0,1,2015
971,Will do.,0,,,0,0,0
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,1,desk dr adamu ismalerauditing accounting manag...,desk dr adamu ismalerauditing accounting manag...,1,1,383
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...",1,dear friend name loi estrada wife mr josephest...,dear friend name loi estrada wife mr josephest...,1,1,1475

## How would work the Bag of Words with Count Vectorizer concept?

In [18]:
# Your code
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer(max_features=1000)

X_train_bow = count_vectorizer.fit_transform(data_train["preprocessed_text"])
X_val_bow = count_vectorizer.transform(data_val["preprocessed_text"])

y_train = data_train["label"]
y_val = data_val["label"]

print("BoW train shape:", X_train_bow.shape)
print("BoW validation shape:", X_val_bow.shape)

bow_words = count_vectorizer.get_feature_names_out()
print("First 20 words:")
print(bow_words[:20])

BoW train shape: (800, 1000)
BoW validation shape: (200, 1000)
First 20 words:
['ab' 'abacha' 'abandoned' 'abidjan' 'able' 'abroad' 'ac' 'accept'
 'acceptance' 'access' 'accord' 'according' 'account' 'accounting'
 'across' 'act' 'action' 'actual' 'actually' 'ad']

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [19]:
# Your code
tfidf_vectorizer = TfidfVectorizer(max_features=1000)

X_train_tfidf = tfidf_vectorizer.fit_transform(data_train["preprocessed_text"])
X_val_tfidf = tfidf_vectorizer.transform(data_val["preprocessed_text"])

print("TF-IDF train shape:", X_train_tfidf.shape)
print("TF-IDF validation shape:", X_val_tfidf.shape)

TF-IDF train shape: (800, 1000)
TF-IDF validation shape: (200, 1000)

## And the Train a Classifier?

In [21]:
# Your code
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

model = MultinomialNB()
model.fit(X_train_tfidf, y_train)
y_pred = model.predict(X_val_tfidf)

print("Accuracy:", accuracy_score(y_val, y_pred))
print()
print("Classification report:")
print(classification_report(y_val, y_pred))
print("Confusion matrix:")
print(confusion_matrix(y_val, y_pred))

Accuracy: 0.97

Classification report:
              precision    recall  f1-score   support

           0       0.99      0.96      0.97       112
           1       0.95      0.99      0.97        88

    accuracy                           0.97       200
   macro avg       0.97      0.97      0.97       200
weighted avg       0.97      0.97      0.97       200

Confusion matrix:
[[107   5]
 [  1  87]]

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [ ]:
# Your code