In [2]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [160]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [132]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

                                                  text  label
0    DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                             Will do.      0
2    Nora--Cheryl has emailed dozens of memos about...      0
3    Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                  fyi      0
..                                                 ...    ...
995  So what's the latest? It sounds contradictory ...      0
996  TRANSFER OF 36,759,000.00 MILLION POUNDS TO YO...      1
997  Barb I will call to explain. Are you back in t...      0
998    Yang on travelNot free tonite.May work tomorrow      0
999  sbwhoeopSunday February 21 2010 7:42 PMHShaunH...      0

[1000 rows x 2 columns]

### Let's divide the training and test set into two partitions

In [133]:
from sklearn.model_selection import train_test_split

X = data.drop(columns=['label'])
y = data['label']

print(type(X))
print(type(y))

<class 'pandas.DataFrame'>
<class 'pandas.Series'>

In [134]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f"Train size: {X_train.shape[0]} rows")
print(f"Test size: {X_test.shape[0]} rows")

Train size: 800 rows
Test size: 200 rows

## Data Preprocessing

In [135]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [136]:
import re
def clean_html(text):
    text = re.sub(r"<script.*?</script>", "", text, flags=re.DOTALL | re.IGNORECASE)
    text = re.sub(r"<style.*?</style>", "", text, flags=re.DOTALL | re.IGNORECASE)
    text = re.sub(r"<!--.*?-->", "", text, flags=re.DOTALL | re.IGNORECASE)
    text = re.sub(r"<.*?>", "", text, flags=re.DOTALL | re.IGNORECASE)
    return text

In [137]:
X_train = X_train.copy()
X_train['preprocessed_text'] = X_train['text'].apply(clean_html)

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [138]:
def clean_word(text):
    text = re.sub(r"^b['\"]", " ", text)
    text = ''.join(char if char not in string.punctuation else ' ' for char in text)
    text = re.sub(r"\d+", " ", text, flags=re.DOTALL)
    text = re.sub(r"\b[a-zA-Z]\b", " ", text)
    text = re.sub(r"^\s*[a-zA-Z]\s+", " ", text)
    text = re.sub(r"\s+", " ", text)
    text = text.lower()
    return text

In [139]:
X_train['preprocessed_text'] = X_train['preprocessed_text'].apply(clean_word)

In [140]:
print("Original:")
print(X_train['text'].iloc[0])

print("\nCleaned:")
print(X_train['preprocessed_text'].iloc[0])

Original:
Dear=2C Good day hope fine=2Cdear am writting this mail with due respect and heartful of tears since we have not known or met ourselves previously I am asking for your assistance=2Ci have will be very glad if you can render me assistance to my situation now=2E I will make my proposal well known if I am given the opportunity=2E I would like to use this opportunity to introduce myself to you=2E Am Miss Johana Johnpaul 24 years old girl from Liberia =2Cthe only daughter of Late Godwin Johnpaul the deputy minister of national security under the leadership of president Charles Taylor of liberia who is now in exile after many innocent soul were killed=2E My father was killed by the government of CharlesTaylor=2Cheaccuse my father of coup attempt and after a month my mother Cynthia was also killed=2E The main reason why I am contacting you now is to seek for your assistance in the area of my future investment and also i want to hand over some huge amount of money to you=2E This money is Ten Millon Five Hundred Thousand US Dollars which was deposited some years ago by my father he made me the sole beneficiary=2Fnext of kin to the money=2E I am now asking you to stand on my behalf to make this claim for the bank=2Cam a girl and too young in age cann't handle this can of transaction=2Ci want you to stand as my foregin partner oversea and also to help me investment the money as well send me your telephone number and pictures ok=2E=2E=2E=2E I have all original copies of the documents concering this money with me here=2CSo please am expecting to hear from you soon=2E My Regards=2C Miss Johana

Cleaned:
dear good day hope fine cdear am writting this mail with due respect and heartful of tears since we have not known or met ourselves previously am asking for your assistance ci have will be very glad if you can render me assistance to my situation now will make my proposal well known if am given the opportunity would like to use this opportunity to introduce myself to you am miss johana johnpaul years old girl from liberia cthe only daughter of late godwin johnpaul the deputy minister of national security under the leadership of president charles taylor of liberia who is now in exile after many innocent soul were killed my father was killed by the government of charlestaylor cheaccuse my father of coup attempt and after month my mother cynthia was also killed the main reason why am contacting you now is to seek for your assistance in the area of my future investment and also want to hand over some huge amount of money to you this money is ten millon five hundred thousand us dollars which was deposited some years ago by my father he made me the sole beneficiary fnext of kin to the money am now asking you to stand on my behalf to make this claim for the bank cam girl and too young in age cann handle this can of transaction ci want you to stand as my foregin partner oversea and also to help me investment the money as well send me your telephone number and pictures ok have all original copies of the documents concering this money with me here cso please am expecting to hear from you soon my regards miss johana

## Now let's work on removing stopwords
Remove the stopwords.

In [141]:
stop_words = set(stopwords.words('english'))

In [142]:
def clean_stopwords(text):
    text = text.split()
    filtered_words = [word for word in text if word not in stop_words]
    return ' '.join(filtered_words)

In [143]:
X_train['preprocessed_text'] = X_train['preprocessed_text'].apply(clean_stopwords)

In [144]:
print("Original:")
print(X_train['text'].iloc[0])

print("\nCleaned:")
print(X_train['preprocessed_text'].iloc[0])

Original:
Dear=2C Good day hope fine=2Cdear am writting this mail with due respect and heartful of tears since we have not known or met ourselves previously I am asking for your assistance=2Ci have will be very glad if you can render me assistance to my situation now=2E I will make my proposal well known if I am given the opportunity=2E I would like to use this opportunity to introduce myself to you=2E Am Miss Johana Johnpaul 24 years old girl from Liberia =2Cthe only daughter of Late Godwin Johnpaul the deputy minister of national security under the leadership of president Charles Taylor of liberia who is now in exile after many innocent soul were killed=2E My father was killed by the government of CharlesTaylor=2Cheaccuse my father of coup attempt and after a month my mother Cynthia was also killed=2E The main reason why I am contacting you now is to seek for your assistance in the area of my future investment and also i want to hand over some huge amount of money to you=2E This money is Ten Millon Five Hundred Thousand US Dollars which was deposited some years ago by my father he made me the sole beneficiary=2Fnext of kin to the money=2E I am now asking you to stand on my behalf to make this claim for the bank=2Cam a girl and too young in age cann't handle this can of transaction=2Ci want you to stand as my foregin partner oversea and also to help me investment the money as well send me your telephone number and pictures ok=2E=2E=2E=2E I have all original copies of the documents concering this money with me here=2CSo please am expecting to hear from you soon=2E My Regards=2C Miss Johana

Cleaned:
dear good day hope fine cdear writting mail due respect heartful tears since known met previously asking assistance ci glad render assistance situation make proposal well known given opportunity would like use opportunity introduce miss johana johnpaul years old girl liberia cthe daughter late godwin johnpaul deputy minister national security leadership president charles taylor liberia exile many innocent soul killed father killed government charlestaylor cheaccuse father coup attempt month mother cynthia also killed main reason contacting seek assistance area future investment also want hand huge amount money money ten millon five hundred thousand us dollars deposited years ago father made sole beneficiary fnext kin money asking stand behalf make claim bank cam girl young age cann handle transaction ci want stand foregin partner oversea also help investment money well send telephone number pictures ok original copies documents concering money cso please expecting hear soon regards miss johana

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [145]:
def text_snowball(text):
    text = text.split()
    lemmatized_words = [snowball.stem(word) for word in text]
    return ' '.join(lemmatized_words)

In [146]:
X_train['preprocessed_text'] = X_train['preprocessed_text'].apply(text_snowball)

In [147]:
print("Original:")
print(X_train['text'].iloc[0])

print("\nCleaned:")
print(X_train['preprocessed_text'].iloc[0])

Original:
Dear=2C Good day hope fine=2Cdear am writting this mail with due respect and heartful of tears since we have not known or met ourselves previously I am asking for your assistance=2Ci have will be very glad if you can render me assistance to my situation now=2E I will make my proposal well known if I am given the opportunity=2E I would like to use this opportunity to introduce myself to you=2E Am Miss Johana Johnpaul 24 years old girl from Liberia =2Cthe only daughter of Late Godwin Johnpaul the deputy minister of national security under the leadership of president Charles Taylor of liberia who is now in exile after many innocent soul were killed=2E My father was killed by the government of CharlesTaylor=2Cheaccuse my father of coup attempt and after a month my mother Cynthia was also killed=2E The main reason why I am contacting you now is to seek for your assistance in the area of my future investment and also i want to hand over some huge amount of money to you=2E This money is Ten Millon Five Hundred Thousand US Dollars which was deposited some years ago by my father he made me the sole beneficiary=2Fnext of kin to the money=2E I am now asking you to stand on my behalf to make this claim for the bank=2Cam a girl and too young in age cann't handle this can of transaction=2Ci want you to stand as my foregin partner oversea and also to help me investment the money as well send me your telephone number and pictures ok=2E=2E=2E=2E I have all original copies of the documents concering this money with me here=2CSo please am expecting to hear from you soon=2E My Regards=2C Miss Johana

Cleaned:
dear good day hope fine cdear writ mail due respect heart tear sinc known met previous ask assist ci glad render assist situat make propos well known given opportun would like use opportun introduc miss johana johnpaul year old girl liberia cthe daughter late godwin johnpaul deputi minist nation secur leadership presid charl taylor liberia exil mani innoc soul kill father kill govern charlestaylor cheaccus father coup attempt month mother cynthia also kill main reason contact seek assist area futur invest also want hand huge amount money money ten millon five hundr thousand us dollar deposit year ago father made sole beneficiari fnext kin money ask stand behalf make claim bank cam girl young age cann handl transact ci want stand foregin partner oversea also help invest money well send telephon number pictur ok origin copi document concer money cso pleas expect hear soon regard miss johana

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [151]:
data_train = X_train.copy()
data_train['label'] = y_train
data_train.head(2)

,text,preprocessed_text,label
442,Dear=2C Good day hope fine=2Cdear am writting ...,dear good day hope fine cdear writ mail due re...,1
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,mr henri kaboreth chief auditor inchargeforeig...,1

In [ ]:
all_ham_texts = " ".join(data_train[data_train['label']==0]['preprocessed_text'])
all_spam_texts = " ".join(data_train[data_train['label']==1]['preprocessed_text'])

ham_words = all_ham_texts.split()
spam_words = all_spam_texts.split()

In [157]:
from collections import Counter

top_ham_10 = Counter(ham_words).most_common(10)
top_spam_10 = Counter(spam_words).most_common(10)

display(top_ham_10)
display(top_spam_10)

[('work', 97),
 ('presid', 97),
 ('state', 96),
 ('call', 94),
 ('would', 92),
 ('mr', 85),
 ('obama', 82),
 ('percent', 80),
 ('time', 73),
 ('one', 69)]

[('money', 756),
 ('account', 701),
 ('bank', 685),
 ('fund', 606),
 ('us', 597),
 ('transact', 437),
 ('transfer', 432),
 ('busi', 415),
 ('countri', 397),
 ('foreign', 394)]

## Extra features

In [158]:
X_test = X_test.copy()
X_test['preprocessed_text'] = X_test['text'].apply(clean_html)
X_test['preprocessed_text'] = X_test['preprocessed_text'].apply(clean_word)
X_test['preprocessed_text'] = X_test['preprocessed_text'].apply(clean_stopwords)
X_test['preprocessed_text'] = X_test['preprocessed_text'].apply(text_snowball)

data_test = X_test.copy()
data_test['label'] = y_test
data_test.head(2)

,text,preprocessed_text,label
222,STRICTLY PERSONALPermit me to introduce myself...,strict personalpermit introduc mr joyc zuma ba...,1
824,Dear Nancy--I very much want to meet and we've...,dear nanci much want meet tri pin schedul enou...,0

In [159]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['preprocessed_text'].str.contains(money_simbol_list)*1
data_train['suspicious_words'] = data_train['preprocessed_text'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['preprocessed_text'].apply(lambda x: len(x)) 

data_test['money_mark'] = data_test['preprocessed_text'].str.contains(money_simbol_list)*1
data_test['suspicious_words'] = data_test['preprocessed_text'].str.contains(suspicious_words)*1
data_test['text_len'] = data_test['preprocessed_text'].apply(lambda x: len(x)) 

data_train.head()

,text,preprocessed_text,label,money_mark,suspicious_words,text_len
442,Dear=2C Good day hope fine=2Cdear am writting ...,dear good day hope fine cdear writ mail due re...,1,1,1,901
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,mr henri kaboreth chief auditor inchargeforeig...,1,0,1,1710
971,Will do.,,0,0,0,0
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,desk dr adamu ismaleraudit account manag bank ...,1,1,1,347
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...",dear friend name loi estrada wife mr josephest...,1,1,1,1304

In [165]:
data_train.drop(columns=['text'])
data_train.head()

,text,preprocessed_text,label,money_mark,suspicious_words,text_len
442,Dear=2C Good day hope fine=2Cdear am writting ...,dear good day hope fine cdear writ mail due re...,1,1,1,901
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,mr henri kaboreth chief auditor inchargeforeig...,1,0,1,1710
971,Will do.,,0,0,0,0
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,desk dr adamu ismaleraudit account manag bank ...,1,1,1,347
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...",dear friend name loi estrada wife mr josephest...,1,1,1,1304

## How would work the Bag of Words with Count Vectorizer concept?

In [174]:
vectorizer = CountVectorizer()
X_train_counts = vectorizer.fit_transform(data_train['preprocessed_text'])
X_test_counts = vectorizer.transform(data_test['preprocessed_text'])

In [175]:
print("Bag of Words:\n", X_train_counts.toarray())
print("Vocabulary:", vectorizer.get_feature_names_out())

Bag of Words:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Vocabulary: ['aa' 'aaa' 'aabeiawaeaambiqaceqedeqh' ... 'â½tranger' 'â½x' 'â½ã']

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [176]:
tfidf_vectorizer = TfidfVectorizer()
X_train_counts_tfidf = tfidf_vectorizer.fit_transform(data_train['preprocessed_text'])
X_test_counts_tfidf = tfidf_vectorizer.transform(data_test['preprocessed_text'])

In [177]:
print("TF-IDF:\n", data_train_counts_tfidf.toarray())
print("Vocabulary:", tfidf_vectorizer.get_feature_names_out())

TF-IDF:
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Vocabulary: ['aa' 'aaa' 'aabeiawaeaambiqaceqedeqh' ... 'â½tranger' 'â½x' 'â½ã']

## And the Train a Classifier?

In [178]:
y_train = data_train['label']
y_test = data_test['label']

In [179]:
from sklearn.naive_bayes import MultinomialNB

nb_model = MultinomialNB()
nb_model.fit(X_train_counts, y_train)

print("Model trained")

Model trained

In [180]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
y_pred = nb_model.predict(X_test_counts)

print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print("\nClassification Report: ")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix: ")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.975

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.96      0.98       112
           1       0.95      1.00      0.97        88

    accuracy                           0.97       200
   macro avg       0.97      0.98      0.97       200
weighted avg       0.98      0.97      0.98       200


Confusion Matrix:
[[107   5]
 [  0  88]]

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).