In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

/var/folders/py/840vkq0j4fdd3xpc7gvbrnbm0000gn/T/ipykernel_34246/3777615979.py:1: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import display, HTML

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [3]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv", encoding="latin-1")

# Reduce the training set to speed up development
# Modify for final system
data = data.head(1000)

print(data.shape)

# Replace missing values with empty strings
data.fillna("", inplace=True)

(1000, 2)

### Let's divide the training and test set into two partitions

In [4]:
# Inspect the dataset before splitting
display(data.head())
print(data.columns)

                                                text  label
0  DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                           Will do.      0
2  Nora--Cheryl has emailed dozens of memos about...      0
3  Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                fyi      0

Index(['text', 'label'], dtype='object')

In [5]:
# Split the dataset into training and validation sets
from sklearn.model_selection import train_test_split

data_train, data_val = train_test_split(
    data,
    test_size=0.2,
    random_state=42,
    stratify=data["label"]
)

# Check the sizes
print("Training set:", data_train.shape)
print("Validation set:", data_val.shape)

# Check the class balance
print("\nTraining labels:")
print(data_train["label"].value_counts(normalize=True))

print("\nValidation labels:")
print(data_val["label"].value_counts(normalize=True))

Training set: (800, 2)
Validation set: (200, 2)

Training labels:
label
0    0.5575
1    0.4425
Name: proportion, dtype: float64

Validation labels:
label
0    0.56
1    0.44
Name: proportion, dtype: float64

## Data Preprocessing

In [6]:
import nltk

nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/nsolebna/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [7]:
import string
from nltk.corpus import stopwords

print(string.punctuation)
print(stopwords.words("english")[100:110])

from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer("english")

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [8]:
# Clean HTML, JavaScript/CSS and HTML comments
import re

def clean_html(text):
    # Remove inline JavaScript and CSS
    text = re.sub(r"<script.*?>.*?</script>", " ", text, flags=re.DOTALL | re.IGNORECASE)
    text = re.sub(r"<style.*?>.*?</style>", " ", text, flags=re.DOTALL | re.IGNORECASE)

    # Remove HTML comments
    text = re.sub(r"<!--.*?-->", " ", text, flags=re.DOTALL)

    # Remove remaining HTML tags
    text = re.sub(r"<.*?>", " ", text)

    return text

# Apply to both training and validation text
data_train["preprocessed_text"] = data_train["text"].apply(clean_html)
data_val["preprocessed_text"] = data_val["text"].apply(clean_html)

# Check the result
data_train[["text", "preprocessed_text"]].head()

,text,preprocessed_text
442,Dear=2C Good day hope fine=2Cdear am writting ...,Dear=2C Good day hope fine=2Cdear am writting ...
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...
971,Will do.,Will do.
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...","Dear Friend, My name is LOI C.ESTRADA,The wife..."

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [9]:
# Further clean the text
def clean_text(text):
    # Remove special characters
    text = re.sub(r"[^a-zA-Z\s]", " ", text)

    # Remove numbers
    text = re.sub(r"\d+", " ", text)

    # Remove single characters
    text = re.sub(r"\b[a-zA-Z]\b", " ", text)

    # Remove a prefixed 'b' such as b'hello'
    text = re.sub(r"^b\s+", "", text)

    # Replace multiple spaces with one space
    text = re.sub(r"\s+", " ", text)

    # Convert to lowercase
    text = text.lower().strip()

    return text

# Apply the cleaning function
data_train["preprocessed_text"] = data_train["preprocessed_text"].apply(clean_text)
data_val["preprocessed_text"] = data_val["preprocessed_text"].apply(clean_text)

# Check the result
data_train[["text", "preprocessed_text"]].head()

,text,preprocessed_text
442,Dear=2C Good day hope fine=2Cdear am writting ...,dear good day hope fine cdear am writting this...
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,from mr henry kaborethe chief auditor incharge...
971,Will do.,will do
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,from the desk of dr adamu ismalerauditing and ...
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...",dear friend my name is loi estrada the wife of...

## Now let's work on removing stopwords
Remove the stopwords.

In [10]:
# Remove English stopwords

stop_words = set(stopwords.words("english"))

def remove_stopwords(text):
    words = text.split()
    filtered_words = [word for word in words if word not in stop_words]
    return " ".join(filtered_words)

# Apply to training and validation data
data_train["preprocessed_text"] = data_train["preprocessed_text"].apply(remove_stopwords)
data_val["preprocessed_text"] = data_val["preprocessed_text"].apply(remove_stopwords)

# Check the result
data_train[["text", "preprocessed_text"]].head()

,text,preprocessed_text
442,Dear=2C Good day hope fine=2Cdear am writting ...,dear good day hope fine cdear writting mail du...
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,mr henry kaborethe chief auditor inchargeforei...
971,Will do.,
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,desk dr adamu ismalerauditing accounting manag...
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...",dear friend name loi estrada wife mr josephest...

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [11]:
import nltk

nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/nsolebna/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/nsolebna/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [12]:
# Lemmatize words to their base form
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    words = text.split()
    lemmatized_words = [lemmatizer.lemmatize(word) for word in words]
    return " ".join(lemmatized_words)

# Apply to training and validation data
data_train["preprocessed_text"] = data_train["preprocessed_text"].apply(lemmatize_text)
data_val["preprocessed_text"] = data_val["preprocessed_text"].apply(lemmatize_text)

# Check the result
data_train[["text", "preprocessed_text"]].head()

,text,preprocessed_text
442,Dear=2C Good day hope fine=2Cdear am writting ...,dear good day hope fine cdear writting mail du...
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,mr henry kaborethe chief auditor inchargeforei...
971,Will do.,
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,desk dr adamu ismalerauditing accounting manag...
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...",dear friend name loi estrada wife mr josephest...

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

# Create a Bag-of-Words representation
count_vectorizer = CountVectorizer()

# Fit only on the training text
X_bow = count_vectorizer.fit_transform(data_train["preprocessed_text"])

# Get the vocabulary
words = count_vectorizer.get_feature_names_out()

# Sum word counts across all training messages
word_counts = X_bow.sum(axis=0).A1

# Put counts into a DataFrame
word_freq = pd.DataFrame({
    "word": words,
    "count": word_counts
})

# Show the 10 most frequent words
word_freq.sort_values("count", ascending=False).head(10)

              word  count
15128        money    767
231        account    680
2565          bank    624
8685          fund    601
15254           mr    474
4961       country    448
3446      business    439
23303  transaction    435
15658         nbsp    387
14915      million    374

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

def top_words_by_label(df, label_value, n=10):
    # Select only messages from one class
    texts = df.loc[df["label"] == label_value, "preprocessed_text"]

    # Build a Bag-of-Words matrix for that class
    vectorizer = CountVectorizer()
    X = vectorizer.fit_transform(texts)

    # Get words and their total counts
    words = vectorizer.get_feature_names_out()
    counts = X.sum(axis=0).A1

    # Return the top n words
    return (
        pd.DataFrame({
            "word": words,
            "count": counts
        })
        .sort_values("count", ascending=False)
        .head(n)
    )

print("Top HAM words:")
display(top_words_by_label(data_train, 0))

print("Top SPAM words:")
display(top_words_by_label(data_train, 1))

Top HAM words:

           word  count
4972      state     97
4066  president     95
5934      would     92
3390         mr     90
3870    percent     80
3585      obama     80
809        call     77
5915       work     72
5368       time     70
3673        one     69

Top SPAM words:

              word  count
13039        money    761
211        account    674
2238          bank    615
7373          fund    600
19857  transaction    435
2949      business    412
4165       country    401
13498         nbsp    387
13149           mr    384
12863      million    364

## Extra features

In [15]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['preprocessed_text'].str.contains(money_simbol_list)*1
data_train['suspicious_words'] = data_train['preprocessed_text'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['preprocessed_text'].apply(lambda x: len(x)) 

data_val['money_mark'] = data_val['preprocessed_text'].str.contains(money_simbol_list)*1
data_val['suspicious_words'] = data_val['preprocessed_text'].str.contains(suspicious_words)*1
data_val['text_len'] = data_val['preprocessed_text'].apply(lambda x: len(x)) 

data_train.head()

,text,label,preprocessed_text,money_mark,suspicious_words,text_len
442,Dear=2C Good day hope fine=2Cdear am writting ...,1,dear good day hope fine cdear writting mail du...,1,1,998
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,1,mr henry kaborethe chief auditor inchargeforei...,0,1,1946
971,Will do.,0,,0,0,0
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,1,desk dr adamu ismalerauditing accounting manag...,1,1,383
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...",1,dear friend name loi estrada wife mr josephest...,1,1,1475

## How would work the Bag of Words with Count Vectorizer concept?

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

# Create the Bag-of-Words vectorizer
count_vectorizer = CountVectorizer()

# Learn the vocabulary from TRAINING data only
X_train_bow = count_vectorizer.fit_transform(
    data_train["preprocessed_text"]
)

# Transform validation data using the SAME vocabulary
X_val_bow = count_vectorizer.transform(
    data_val["preprocessed_text"]
)

# Labels
y_train = data_train["label"]
y_val = data_val["label"]

# Check the matrix shapes
print("Training BoW shape:", X_train_bow.shape)
print("Validation BoW shape:", X_val_bow.shape)

# Show number of learned words
print("Vocabulary size:", len(count_vectorizer.get_feature_names_out()))

Training BoW shape: (800, 28199)
Validation BoW shape: (200, 28199)
Vocabulary size: 28199

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Create the TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Learn vocabulary and weights from training data only
X_train_tfidf = tfidf_vectorizer.fit_transform(
    data_train["preprocessed_text"]
)

# Transform validation data with the same vocabulary
X_val_tfidf = tfidf_vectorizer.transform(
    data_val["preprocessed_text"]
)

print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Validation TF-IDF shape:", X_val_tfidf.shape)

Training TF-IDF shape: (800, 28199)
Validation TF-IDF shape: (200, 28199)

## And the Train a Classifier?

In [18]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Train with Bag of Words
nb_bow = MultinomialNB()
nb_bow.fit(X_train_bow, y_train)

# Predict on validation data
y_pred_bow = nb_bow.predict(X_val_bow)

print("Bag of Words accuracy:", accuracy_score(y_val, y_pred_bow))
print("\nClassification report:")
print(classification_report(y_val, y_pred_bow))

Bag of Words accuracy: 0.97

Classification report:
              precision    recall  f1-score   support

           0       1.00      0.95      0.97       112
           1       0.94      1.00      0.97        88

    accuracy                           0.97       200
   macro avg       0.97      0.97      0.97       200
weighted avg       0.97      0.97      0.97       200

In [19]:
# Train with TF-IDF
nb_tfidf = MultinomialNB()
nb_tfidf.fit(X_train_tfidf, y_train)

# Predict on validation data
y_pred_tfidf = nb_tfidf.predict(X_val_tfidf)

print("TF-IDF accuracy:", accuracy_score(y_val, y_pred_tfidf))
print("\nClassification report:")
print(classification_report(y_val, y_pred_tfidf))

TF-IDF accuracy: 0.95

Classification report:
              precision    recall  f1-score   support

           0       1.00      0.91      0.95       112
           1       0.90      1.00      0.95        88

    accuracy                           0.95       200
   macro avg       0.95      0.96      0.95       200
weighted avg       0.96      0.95      0.95       200

-Using the same classifier, Bag of Words achieved 97% accuracy, while TF-IDF achieved 95%, so Bag of Words performed slightly better on this validation set.

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [20]:
# Compare different feature sets using the SAME classifier
from scipy.sparse import hstack, csr_matrix
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, f1_score
import pandas as pd

# Extra handcrafted features
extra_cols = ["money_mark", "suspicious_words", "text_len"]

X_train_extra = csr_matrix(data_train[extra_cols].values)
X_val_extra = csr_matrix(data_val[extra_cols].values)

# Combine text representations with extra features
X_train_bow_extra = hstack([X_train_bow, X_train_extra])
X_val_bow_extra = hstack([X_val_bow, X_val_extra])

X_train_tfidf_extra = hstack([X_train_tfidf, X_train_extra])
X_val_tfidf_extra = hstack([X_val_tfidf, X_val_extra])

# Store all feature setups
feature_sets = {
    "Bag of Words": (X_train_bow, X_val_bow),
    "TF-IDF": (X_train_tfidf, X_val_tfidf),
    "Bag of Words + extra features": (X_train_bow_extra, X_val_bow_extra),
    "TF-IDF + extra features": (X_train_tfidf_extra, X_val_tfidf_extra)
}

results = []

# Train exactly the same model on each feature representation
for name, (X_train, X_val) in feature_sets.items():

    model = MultinomialNB()
    model.fit(X_train, y_train)

    y_pred = model.predict(X_val)

    results.append({
        "Feature set": name,
        "Accuracy": accuracy_score(y_val, y_pred),
        "F1 spam": f1_score(y_val, y_pred, pos_label=1)
    })

results_df = pd.DataFrame(results).sort_values(
    "Accuracy",
    ascending=False
)

results_df

                     Feature set  Accuracy   F1 spam
0                   Bag of Words      0.97  0.967033
1                         TF-IDF      0.95  0.946237
2  Bag of Words + extra features      0.85  0.854369
3        TF-IDF + extra features      0.61  0.692913

- Bag of Words performed best, achieving 97% accuracy and an F1-score of about 0.97 for spam. TF-IDF performed slightly worse, while adding the handcrafted features reduced performance substantially. Therefore, the simplest Bag-of-Words representation was the best choice for this dataset and classifier.