In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

C:\Users\Phiph\AppData\Local\Temp\ipykernel_3800\3777615979.py:1: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython.display
  from IPython.core.display import display, HTML

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [3]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)
display(data)

(1000, 2)

                                                  text  label
0    DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                             Will do.      0
2    Nora--Cheryl has emailed dozens of memos about...      0
3    Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                  fyi      0
..                                                 ...    ...
995  So what's the latest? It sounds contradictory ...      0
996  TRANSFER OF 36,759,000.00 MILLION POUNDS TO YO...      1
997  Barb I will call to explain. Are you back in t...      0
998    Yang on travelNot free tonite.May work tomorrow      0
999  sbwhoeopSunday February 21 2010 7:42 PMHShaunH...      0

[1000 rows x 2 columns]

### Let's divide the training and test set into two partitions

In [4]:
from sklearn.model_selection import train_test_split

X = data['text'] 
y = data['label']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Train shape : {X_train.shape}")
print(f"Test shape : {X_test.shape}")

Train shape : (800,)
Test shape : (200,)

## Data Preprocessing

In [5]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [6]:
import re

def clean_html(text):
    # JS/CSS
    text = re.sub(r'<(script|style).*?>.*?</\1>', '', text, flags=re.DOTALL)
    
    # HTML comments
    text = re.sub(r'<!--.*?-->', '', text, flags=re.DOTALL)
    
    # Remaining HTML tags
    text = re.sub(r'<.*?>', '', text)
    
    return text

data['clean_text'] = data['text'].apply(clean_html)
display(data['clean_text'])

0      DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...
1                                               Will do.
2      Nora--Cheryl has emailed dozens of memos about...
3      Dear Sir=2FMadam=2C I know that this proposal ...
4                                                    fyi
                             ...
995    So what's the latest? It sounds contradictory ...
996    TRANSFER OF 36,759,000.00 MILLION POUNDS TO YO...
997    Barb I will call to explain. Are you back in t...
998      Yang on travelNot free tonite.May work tomorrow
999    sbwhoeopSunday February 21 2010 7:42 PMHShaunH...
Name: clean_text, Length: 1000, dtype: object

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [7]:
def preprocess_text(text):
    text = text.lower()
    # Special characters, numbers and punctuation
    text = re.sub(r'[^a-z0-9\s]', '', text)
    
    # Remove singles characters
    text = re.sub(r'\s+[a-z]\s+', '', text)
    # Remove single characters from the start
    text = re.sub(r"^[a-z]\s+", "", text)
    
    # Convert multiple spaces to single space
    text = re.sub(r'\s+', ' ', text).strip()
    
    # Prefixed 'b'
    text = re.sub(r"^b\s+", "", text)
    
    return text

data['clean_text'] = data['clean_text'].apply(preprocess_text)
display(data['clean_text'])

0      dear sir strictlyprivate business proposalam m...
1                                                will do
2      noracheryl has emailed dozens of memos about h...
3      dear sir2fmadam2cknow that this proposal might...
4                                                    fyi
                             ...
995    so whats the latest it sounds contradictory an...
996    transfer of 3675900000 million pounds to youra...
997    barbwill call to explain are you back in the c...
998       yang on travelnot free tonitemay work tomorrow
999    sbwhoeopsunday february 21 2010 742 pmhshaunh ...
Name: clean_text, Length: 1000, dtype: object

## Now let's work on removing stopwords
Remove the stopwords.

In [8]:
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    words = text.split()
    return " ".join([w for w in words if w not in stop_words])

data['clean_text'] = data['clean_text'].apply(remove_stopwords)
display(data['clean_text'])

0      dear sir strictlyprivate business proposalam m...
1
2      noracheryl emailed dozens memos haiti weekend ...
3      dear sir2fmadam2cknow proposal might besurpris...
4                                                    fyi
                             ...
995    whats latest sounds contradictory af decide sh...
996    transfer 3675900000 million pounds youraccount...
997                 barbwill call explain back country h
998          yang travelnot free tonitemay work tomorrow
999    sbwhoeopsunday february 21 2010 742 pmhshaunh ...
Name: clean_text, Length: 1000, dtype: object

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [9]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    words = text.split()
    return " ".join([lemmatizer.lemmatize(w) for w in words])

data['clean_text'] = data['clean_text'].apply(lemmatize_text)
display(data['clean_text'])

0      dear sir strictlyprivate business proposalam m...
1
2      noracheryl emailed dozen memo haiti weekend pl...
3      dear sir2fmadam2cknow proposal might besurpris...
4                                                    fyi
                             ...
995    whats latest sound contradictory af decide sha...
996    transfer 3675900000 million pound youraccountm...
997                 barbwill call explain back country h
998          yang travelnot free tonitemay work tomorrow
999    sbwhoeopsunday february 21 2010 742 pmhshaunh ...
Name: clean_text, Length: 1000, dtype: object

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [10]:
from collections import Counter

# Séparer les spams et les hams
spam_words = " ".join(data[data['label']==1]['clean_text']).split()
ham_words = " ".join(data[data['label']==0]['clean_text']).split()

print("Top 10 Spams:", Counter(spam_words).most_common(10))
print("Top 10 Hams:", Counter(ham_words).most_common(10))

Top 10 Spams: [('money', 902), ('account', 772), ('fund', 689), ('bank', 683), ('u', 462), ('business', 413), ('country', 384), ('transaction', 383), ('transfer', 377), ('million', 359)]
Top 10 Hams: [('2', 166), ('1', 134), ('u', 112), ('3', 107), ('would', 100), ('president', 92), ('pm', 92), ('state', 83), ('call', 79), ('secretary', 74)]

## Extra features

In [11]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data['money_mark'] = data['clean_text'].str.contains(money_simbol_list)*1
data['suspicious_words'] = data['clean_text'].str.contains(suspicious_words)*1
data['text_len'] = data['clean_text'].apply(lambda x: len(x)) 

data

,text,label,clean_text,money_mark,suspicious_words,text_len
0,"DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...",1,dear sir strictlyprivate business proposalam m...,1,1,1545
1,Will do.,0,,0,0,0
2,Nora--Cheryl has emailed dozens of memos about...,0,noracheryl emailed dozen memo haiti weekend pl...,0,0,110
3,Dear Sir=2FMadam=2C I know that this proposal ...,1,dear sir2fmadam2cknow proposal might besurpris...,1,1,1491
4,fyi,0,fyi,0,0,3
...,...,...,...,...,...,...
995,So what's the latest? It sounds contradictory ...,0,whats latest sound contradictory af decide sha...,0,0,65
996,"TRANSFER OF 36,759,000.00 MILLION POUNDS TO YO...",1,transfer 3675900000 million pound youraccountm...,1,1,1965
997,Barb I will call to explain. Are you back in t...,0,barbwill call explain back country h,0,0,36
998,Yang on travelNot free tonite.May work tomorrow,0,yang travelnot free tonitemay work tomorrow,0,1,43
999,sbwhoeopSunday February 21 2010 7:42 PMHShaunH...,0,sbwhoeopsunday february 21 2010 742 pmhshaunh ...,0,0,146

## How would work the Bag of Words with Count Vectorizer concept?

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

bow_vectorizer = CountVectorizer()
X_bow = bow_vectorizer.fit_transform(data['clean_text'])
print("Shape BoW:", X_bow.shape)

Shape BoW: (1000, 23813)

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [13]:
tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(data['clean_text'])
print("Shape TF-IDF:", X_tfidf.shape)

Shape TF-IDF: (1000, 23813)

## And the Train a Classifier?

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from scipy.sparse import hstack
from sklearn.metrics import accuracy_score

extra_features = ['money_mark', 'suspicious_words', 'text_len']
X_extra = data[extra_features].values

# TF-IDF + Extra
X_train_final = hstack([X_tfidf, X_extra])

# Train
mnb = MultinomialNB()
mnb.fit(X_train_final, y_train)

# Prediction
X_test_final = hstack([X_tfidf, data[extra_features].values])
y_pred = mnb.predict(X_test_final)

print("Accuracy:", accuracy_score(y_test, y_pred))

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [ ]:
# Your code