In [1]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [3]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

### Let's divide the training and test set into two partitions

In [4]:
from sklearn.model_selection import train_test_split

data_train, data_val = train_test_split(data, test_size=0.2, random_state=42)
print(data_train.shape, data_val.shape)

(800, 2) (200, 2)

## Data Preprocessing

In [5]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [7]:
import re

def clean_html(text):
    text = re.sub(r'<script.*?>.*?</script>', ' ', text, flags=re.DOTALL)   
    text = re.sub(r'<style.*?>.*?</style>', ' ', text, flags=re.DOTALL)     
    text = re.sub(r'<!--.*?-->', ' ', text, flags=re.DOTALL)                
    text = re.sub(r'<.*?>', ' ', text)                                      
    return text

data_train['preprocessed_text'] = data_train['text'].apply(clean_html)
data_val['preprocessed_text'] = data_val['text'].apply(clean_html)

data_train[['text', 'preprocessed_text']].head()

,text,preprocessed_text
29,"----------- REGARDS, MR NELSON SMITH.KINDLY RE...","----------- REGARDS, MR NELSON SMITH.KINDLY RE..."
535,I have not been able to reach oscar this am. W...,I have not been able to reach oscar this am. W...
695,; Huma Abedin B6I'm checking with Pat on the 5...,; Huma Abedin B6I'm checking with Pat on the 5...
557,I can have it announced here on Monday - can't...,I can have it announced here on Monday - can't...
836,BANK OF AFRICAAGENCE SAN PEDRO14 BP 1210 S...,BANK OF AFRICAAGENCE SAN PEDRO14 BP 1210 S...

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [8]:
def clean_text(text):
    text = re.sub(r'\W', ' ', text)              
    text = re.sub(r'\d', ' ', text)               
    text = re.sub(r'\s+[a-zA-Z]\s+', ' ', text)   
    text = re.sub(r'\^[a-zA-Z]\s+', ' ', text)    
    text = re.sub(r'\s+', ' ', text)              
    text = re.sub(r'^b\s+', '', text)             
    return text.lower().strip()

data_train['preprocessed_text'] = data_train['preprocessed_text'].apply(clean_text)
data_val['preprocessed_text'] = data_val['preprocessed_text'].apply(clean_text)

data_train[['text', 'preprocessed_text']].head()

,text,preprocessed_text
29,"----------- REGARDS, MR NELSON SMITH.KINDLY RE...",regards mr nelson smith kindly reply me on my ...
535,I have not been able to reach oscar this am. W...,i have not been able to reach oscar this am we...
695,; Huma Abedin B6I'm checking with Pat on the 5...,huma abedin i checking with pat on the will wo...
557,I can have it announced here on Monday - can't...,i can have it announced here on monday can today
836,BANK OF AFRICAAGENCE SAN PEDRO14 BP 1210 S...,bank of africaagence san pedro bp san pedro co...

## Now let's work on removing stopwords
Remove the stopwords.

In [9]:
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    return ' '.join([w for w in text.split() if w not in stop_words])

data_train['preprocessed_text'] = data_train['preprocessed_text'].apply(remove_stopwords)
data_val['preprocessed_text'] = data_val['preprocessed_text'].apply(remove_stopwords)

data_train[['text', 'preprocessed_text']].head()

,text,preprocessed_text
29,"----------- REGARDS, MR NELSON SMITH.KINDLY RE...",regards mr nelson smith kindly reply private e...
535,I have not been able to reach oscar this am. W...,able reach oscar supposed send pdb receive
695,; Huma Abedin B6I'm checking with Pat on the 5...,huma abedin checking pat work jack jake rest a...
557,I can have it announced here on Monday - can't...,announced monday today
836,BANK OF AFRICAAGENCE SAN PEDRO14 BP 1210 S...,bank africaagence san pedro bp san pedro cote ...

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [10]:
def stem_text(text):
    return ' '.join([snowball.stem(w) for w in text.split()])

data_train['preprocessed_text'] = data_train['preprocessed_text'].apply(stem_text)
data_val['preprocessed_text'] = data_val['preprocessed_text'].apply(stem_text)

data_train[['text', 'preprocessed_text']].head()

,text,preprocessed_text
29,"----------- REGARDS, MR NELSON SMITH.KINDLY RE...",regard mr nelson smith kind repli privat email...
535,I have not been able to reach oscar this am. W...,abl reach oscar suppos send pdb receiv
695,; Huma Abedin B6I'm checking with Pat on the 5...,huma abedin check pat work jack jake rest also...
557,I can have it announced here on Monday - can't...,announc monday today
836,BANK OF AFRICAAGENCE SAN PEDRO14 BP 1210 S...,bank africaag san pedro bp san pedro cote ivoi...

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [12]:
# Your code
from collections import Counter

spam_words = " ".join(data_train[data_train['label'] == 1]['preprocessed_text']).split()
ham_words = " ".join(data_train[data_train['label'] == 0]['preprocessed_text']).split()

print("Top 10 spam words:", Counter(spam_words).most_common(10))
print("Top 10 ham words:", Counter(ham_words).most_common(10))

Top 10 spam words: [('money', 847), ('account', 779), ('bank', 709), ('fund', 631), ('us', 600), ('transfer', 480), ('e', 475), ('transact', 474), ('foreign', 446), ('busi', 430)]
Top 10 ham words: [('â', 200), ('state', 117), ('pm', 97), ('call', 94), ('would', 94), ('presid', 91), ('work', 90), ('ã', 89), ('time', 84), ('mr', 84)]

## Extra features

In [13]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['preprocessed_text'].str.contains(money_simbol_list)*1
data_train['suspicious_words'] = data_train['preprocessed_text'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['preprocessed_text'].apply(lambda x: len(x)) 

data_val['money_mark'] = data_val['preprocessed_text'].str.contains(money_simbol_list)*1
data_val['suspicious_words'] = data_val['preprocessed_text'].str.contains(suspicious_words)*1
data_val['text_len'] = data_val['preprocessed_text'].apply(lambda x: len(x)) 

data_train.head()

,text,label,preprocessed_text,money_mark,suspicious_words,text_len
29,"----------- REGARDS, MR NELSON SMITH.KINDLY RE...",1,regard mr nelson smith kind repli privat email...,0,0,76
535,I have not been able to reach oscar this am. W...,0,abl reach oscar suppos send pdb receiv,0,0,38
695,; Huma Abedin B6I'm checking with Pat on the 5...,0,huma abedin check pat work jack jake rest also...,0,0,73
557,I can have it announced here on Monday - can't...,0,announc monday today,0,0,20
836,BANK OF AFRICAAGENCE SAN PEDRO14 BP 1210 S...,1,bank africaag san pedro bp san pedro cote ivoi...,1,1,987

## How would work the Bag of Words with Count Vectorizer concept?

In [ ]:
# Your code
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()
X_train_bow = cv.fit_transform(data_train['preprocessed_text'])
X_val_bow = cv.transform(data_val['preprocessed_text'])   

print(X_train_bow.shape)
print(X_val_bow.shape)

(800, 26208)
(200, 26208)

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [15]:
# Your code
tfidf = TfidfVectorizer()
X_train_tfidf = tfidf.fit_transform(data_train['preprocessed_text'])
X_val_tfidf = tfidf.transform(data_val['preprocessed_text'])

print(X_train_tfidf.shape)

(800, 26208)

## And the Train a Classifier?

In [16]:
# Your code
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix

clf = MultinomialNB()
clf.fit(X_train_tfidf, data_train['label'])

y_pred = clf.predict(X_val_tfidf)
print("Accuracy:", accuracy_score(data_val['label'], y_pred))
print(confusion_matrix(data_val['label'], y_pred))

Accuracy: 0.91
[[107  18]
 [  0  75]]

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).