In [123]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

ImportError: cannot import name 'display' from 'IPython.core.display' (c:\Users\ranik\anaconda3\Lib\site-packages\IPython\core\display.py)

In [124]:
from IPython.display import display, HTML

display(HTML("""
<style>
.jp-Notebook {
    width: 100% !important;
}
</style>
"""))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [125]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.corpus import wordnet
from sklearn.model_selection import train_test_split

nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ranik\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [126]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

### Let's divide the training and test set into two partitions

In [127]:
# Your code
data_train, data_val = train_test_split(
    data,
    test_size=0.2,
    random_state=42,
    shuffle=True,
    stratify=data["label"] 
)

In [128]:
data.head(10)

                                                text  label
0  DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                           Will do.      0
2  Nora--Cheryl has emailed dozens of memos about...      0
3  Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                fyi      0
5  sure -- bottom line - you need a special secur...      0
6  Dear Sir,I am Engr. Ugo Nzego with the Enginee...      1
7  Abedin Huma <AbedinH@state.gov>Saturday Novemb...      0
8  There is an Oct 16th George Marshall event at ...      0
9  <P>1 25% for you as the account owner <BR>2 65...      1

## Data Preprocessing

In [129]:
import string
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

### function development

1. **Remove `<script>` and `<style>` blocks first**  
   JavaScript and CSS contain code, not useful linguistic content. These blocks can also span multiple lines, so they are removed before working on simpler HTML structures.

2. **Remove HTML comments before regular tags**  
   HTML comments can contain symbols such as `>`, which may confuse a generic tag-removal pattern. Removing comments early avoids accidentally breaking the cleaning process.

3. **Remove the remaining HTML tags**  
   After scripts, styles, and comments are gone, the remaining tags such as `<p>`, `<a>`, `<div>`, and `</span>` can be safely removed while keeping the actual visible text.

4. **Normalize whitespace**  
   Since each removed element is replaced with a space, the final step collapses repeated spaces, tabs, and line breaks into a single clean space.

This workflow keeps the meaningful textual content while removing structural and technical HTML noise.

In [130]:
import re
# Your code
def clean_html(text):
    # remove script and style blocks
    text = re.sub(  #search for a pattern and substitute it
        pattern = r"<script.*?>.*?</script>" , 
        replacement = " ", 
        original_text = text,
        flags=re.DOTALL | re.IGNORECASE) #match across multiple lines AND ignore case        
        
    text = re.sub(
        pattern = r"<style.*?>.*?</style>", 
        replacement = " ", 
        original_text = text, 
        flags=re.DOTALL | re.IGNORECASE)

    # remove HTML comments
    text = re.sub(
        pattern = r"<!--.*?-->", 
        replacement = " ",
        original_text = text, 
        flags=re.DOTALL)

    # remove remaining HTML tags
    text = re.sub(r"<.*?>", " ", text)

    # normalize extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

### Regex to implement:

1. remove all the special character and numbers

[^a-zA-Z\s]

what does it mean?

- [ ... ]      = character group
- ^            = NOT, when inside square brackets
- a-z          = lowercase letters
- A-Z          = uppercase letters
- \s           = whitespace: spaces, tabs, newlines

-> Match every character that is not a letter and not whitespace.

2. Remove all single characters:

\b[a-zA-Z]\b 
- \b           = start edge of a word
- [a-zA-Z]     = whole word made of exactly one letter
- \b           = end edge of a word

3. Remove prefixed b:

^b\s+
- ^            = START of the string
- b            = the letter
- \s+          = one or more letters after it

4. Remove extra spaces: \s+ 

I will take the function built before and implement to meet those other requirements

### verbose version

In [131]:
def text_cleaner(text):
    # remove script and style blocks
    text = re.sub(  #search for a pattern and substitute it
        pattern = r"<script.*?>.*?</script>" , 
        repl = " ", 
        string = text,
        flags=re.DOTALL | re.IGNORECASE) #match across multiple lines AND ignore case        
        
    text = re.sub(
        pattern = r"<style.*?>.*?</style>", 
        repl = " ", 
        string = text, 
        flags=re.DOTALL | re.IGNORECASE)

    # remove HTML comments
    text = re.sub(
        pattern = r"<!--.*?-->", 
        repl = " ",
        string = text, 
        flags=re.DOTALL)

    # remove remaining HTML tags
    text = re.sub(r"<.*?>", " ", text)

    # remove anything that is not a letter
    text = re.sub(r"[^a-zA-Z\s]", " ", text)

    #lowercase
    text = text.lower()

    # remove single characters
    text = re.sub(r"\b[a-zA-Z]\b", " ", text)

    # remove prefixed b
    text = re.sub(r"^b\s+", " ", text) #useless because we remove all single chars in the step before

    # normalize extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

### final function

In [132]:
# Compact version
def text_cleaner(text):
    patterns = [
        (r"<script.*?>.*?</script>", " ", re.DOTALL | re.IGNORECASE), #inline Javascript and CSS
        (r"<style.*?>.*?</style>", " ", re.DOTALL | re.IGNORECASE),   #inline Javascript and CSS
        (r"<!--.*?-->", " ", re.DOTALL),                              #HTML comments
        (r"<.*?>", " ", 0),                                           #HTML tags
        (r"[^a-zA-Z\s]", " ", 0),                                     #non-letter characters
        (r"\b[a-zA-Z]\b", " ", 0),                                    #single-character words
    ]

    for pattern, replacement, flags in patterns:
        text = re.sub(pattern, replacement, text, flags=flags)

    text = re.sub(r"\s+", " ", text).strip().lower()

    return text

In [133]:
data['text_clean'] = list(map(text_cleaner, data['text']))
print(data.head())
text_clean = data['text_clean'].copy()

                                                text  label  \
0  DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                           Will do.      0
2  Nora--Cheryl has emailed dozens of memos about...      0
3  Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                fyi      0

                                          text_clean
0  dear sir strictly private business proposal am...
1                                            will do
2  nora cheryl has emailed dozens of memos about ...
3  dear sir fmadam know that this proposal might ...
4                                                fyi

## Now let's work on removing stopwords
Remove the stopwords.

In [134]:
# Your code
stop_words = set(stopwords.words('english'))
text_w_stops = text_clean.map(lambda text: text.split())

def remove_stopwords(tokens, stop_words):
    return [token for token in tokens if token not in stop_words]

text_w_stops = text_w_stops.map(lambda tokens: remove_stopwords(tokens, stop_words))
data['text_clean'] = text_w_stops
data.head()

,text,label,text_clean
0,"DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...",1,"[dear, sir, strictly, private, business, propo..."
1,Will do.,0,[]
2,Nora--Cheryl has emailed dozens of memos about...,0,"[nora, cheryl, emailed, dozens, memos, haiti, ..."
3,Dear Sir=2FMadam=2C I know that this proposal ...,1,"[dear, sir, fmadam, know, proposal, might, sur..."
4,fyi,0,[fyi]

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [135]:
# Your code

def lemmatize_docs(docs):
    wordnet_lemma = WordNetLemmatizer()

    def get_wordnet_pos(word):
        """Map POS tag to first character lemmatize() accepts"""
        tag = nltk.pos_tag([word])[0][1][0]#  Get POS tag's first character (e.g., 'N' from 'NN')
        #Maps it to a WordNet-compatible tag
        tag_dict = {"J": wordnet.ADJ,
                    "N": wordnet.NOUN,
                    "V": wordnet.VERB,
                    "R": wordnet.ADV}
        return tag_dict.get(tag, wordnet.NOUN) # returns the word type (Noun if we have not found)
    
    processed_docs = []
    for doc in docs:
        doc = [wordnet_lemma.lemmatize(word, get_wordnet_pos(word)) for word in doc]
        processed_docs.append(doc)

    return processed_docs

lemtext = lemmatize_docs(text_w_stops)

In [136]:
print(text_w_stops.iloc[0],'\n',lemtext[0])
data['preprocessed_text'] = lemtext
data.head()

['dear', 'sir', 'strictly', 'private', 'business', 'proposal', 'mike', 'chukwu', 'manager', 'bills', 'exchange', 'foreign', 'remittance', 'department', 'zenith', 'international', 'bank', 'plc', 'writing', 'letter', 'ask', 'support', 'cooperation', 'carry', 'business', 'opportunity', 'department', 'discovered', 'abandoned', 'sum', 'fifteen', 'million', 'united', 'states', 'dollars', 'account', 'belongs', 'one', 'foreign', 'customers', 'died', 'along', 'entire', 'family', 'wife', 'two', 'children', 'november', 'plane', 'crash', 'since', 'heard', 'death', 'expecting', 'next', 'kin', 'come', 'put', 'claims', 'money', 'heir', 'cannot', 'release', 'fund', 'account', 'unless', 'someone', 'applies', 'claim', 'next', 'kin', 'deceased', 'indicated', 'banking', 'guidelines', 'unfortunately', 'neither', 'family', 'member', 'distant', 'relative', 'ever', 'appeared', 'claim', 'said', 'fund', 'upon', 'discovery', 'officials', 'department', 'agreed', 'make', 'business', 'release', 'total', 'amount', 'account', 'heir', 'fund', 'since', 'one', 'came', 'discovered', 'maintained', 'account', 'bank', 'otherwise', 'fund', 'returned', 'banks', 'treasury', 'unclaimed', 'fund', 'agreed', 'ratio', 'sharing', 'stated', 'thus', 'foreign', 'partner', 'us', 'officials', 'department', 'settlement', 'local', 'foreign', 'expences', 'incurred', 'us', 'course', 'business', 'upon', 'successful', 'completion', 'transfer', 'one', 'colleagues', 'come', 'country', 'mind', 'share', 'intend', 'import', 'agricultural', 'machineries', 'country', 'way', 'recycling', 'fund', 'commence', 'transaction', 'require', 'immediately', 'indicate', 'interest', 'return', 'mail', 'enclose', 'private', 'contact', 'telephone', 'number', 'fax', 'number', 'full', 'name', 'address', 'designated', 'bank', 'coordinates', 'enable', 'us', 'file', 'letter', 'claim', 'appropriate', 'departments', 'necessary', 'approvals', 'transfer', 'made', 'note', 'also', 'transaction', 'must', 'kept', 'strictly', 'confidential', 'nature', 'look', 'forward', 'receiving', 'prompt', 'response', 'regards', 'mr', 'mike', 'chukwu', 'zenith', 'international', 'bank', 'plc']
 ['dear', 'sir', 'strictly', 'private', 'business', 'proposal', 'mike', 'chukwu', 'manager', 'bill', 'exchange', 'foreign', 'remittance', 'department', 'zenith', 'international', 'bank', 'plc', 'write', 'letter', 'ask', 'support', 'cooperation', 'carry', 'business', 'opportunity', 'department', 'discover', 'abandon', 'sum', 'fifteen', 'million', 'united', 'state', 'dollar', 'account', 'belongs', 'one', 'foreign', 'customer', 'die', 'along', 'entire', 'family', 'wife', 'two', 'child', 'november', 'plane', 'crash', 'since', 'heard', 'death', 'expect', 'next', 'kin', 'come', 'put', 'claim', 'money', 'heir', 'cannot', 'release', 'fund', 'account', 'unless', 'someone', 'applies', 'claim', 'next', 'kin', 'decease', 'indicate', 'banking', 'guideline', 'unfortunately', 'neither', 'family', 'member', 'distant', 'relative', 'ever', 'appear', 'claim', 'say', 'fund', 'upon', 'discovery', 'official', 'department', 'agree', 'make', 'business', 'release', 'total', 'amount', 'account', 'heir', 'fund', 'since', 'one', 'come', 'discover', 'maintain', 'account', 'bank', 'otherwise', 'fund', 'return', 'bank', 'treasury', 'unclaimed', 'fund', 'agree', 'ratio', 'share', 'state', 'thus', 'foreign', 'partner', 'u', 'official', 'department', 'settlement', 'local', 'foreign', 'expences', 'incur', 'u', 'course', 'business', 'upon', 'successful', 'completion', 'transfer', 'one', 'colleague', 'come', 'country', 'mind', 'share', 'intend', 'import', 'agricultural', 'machinery', 'country', 'way', 'recycle', 'fund', 'commence', 'transaction', 'require', 'immediately', 'indicate', 'interest', 'return', 'mail', 'enclose', 'private', 'contact', 'telephone', 'number', 'fax', 'number', 'full', 'name', 'address', 'designate', 'bank', 'coordinate', 'enable', 'u', 'file', 'letter', 'claim', 'appropriate', 'department', 'necessary', 'approval', 'transfer', 'make', 'note', 'also', 'transaction', 'must', 'kept', 'strictly', 'confidential', 'nature', 'look', 'forward', 'receive', 'prompt', 'response', 'regard', 'mr', 'mike', 'chukwu', 'zenith', 'international', 'bank', 'plc']

,text,label,text_clean,preprocessed_text
0,"DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...",1,"[dear, sir, strictly, private, business, propo...","[dear, sir, strictly, private, business, propo..."
1,Will do.,0,[],[]
2,Nora--Cheryl has emailed dozens of memos about...,0,"[nora, cheryl, emailed, dozens, memos, haiti, ...","[nora, cheryl, email, dozen, memo, haiti, week..."
3,Dear Sir=2FMadam=2C I know that this proposal ...,1,"[dear, sir, fmadam, know, proposal, might, sur...","[dear, sir, fmadam, know, proposal, might, sur..."
4,fyi,0,[fyi],[fyi]

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [138]:
# Your code
from collections import Counter

# Separate ham and spam
ham_tokens = data.loc[data["label"] == 0, "text_clean"]
spam_tokens = data.loc[data["label"] == 1, "text_clean"]

# Flatten token lists and count words
ham_word_counts = Counter(token for doc in ham_tokens for token in doc)
spam_word_counts = Counter(token for doc in spam_tokens for token in doc)

# Get top 10 words
top_10_ham = ham_word_counts.most_common(10)
top_10_spam = spam_word_counts.most_common(10)

print("Top 10 ham words:")
print(top_10_ham)

print("\nTop 10 spam words:")
print(top_10_spam)

top_10_ham_df = pd.DataFrame(top_10_ham, columns=["word", "count"])
top_10_spam_df = pd.DataFrame(top_10_spam, columns=["word", "count"])

display(top_10_ham_df)
display(top_10_spam_df)

Top 10 ham words:
[('pm', 127), ('state', 113), ('would', 107), ('president', 98), ('mr', 86), ('obama', 84), ('percent', 81), ('call', 78), ('us', 76), ('secretary', 76)]

Top 10 spam words:
[('money', 987), ('account', 840), ('bank', 781), ('us', 737), ('transaction', 544), ('business', 514), ('country', 480), ('fund', 475), ('nbsp', 475), ('million', 442)]

        word  count
0         pm    127
1      state    113
2      would    107
3  president     98
4         mr     86
5      obama     84
6    percent     81
7       call     78
8         us     76
9  secretary     76

          word  count
0        money    987
1      account    840
2         bank    781
3           us    737
4  transaction    544
5     business    514
6      country    480
7         fund    475
8         nbsp    475
9      million    442

In [139]:
data_train, data_val = train_test_split(
    data,
    test_size=0.2,
    random_state=42,
    shuffle=True,
    stratify=data["label"] 
)

## Extra features

In [140]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['preprocessed_text'].str.contains(money_simbol_list)*1
data_train['suspicious_words'] = data_train['preprocessed_text'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['preprocessed_text'].apply(lambda x: len(x)) 

data_val['money_mark'] = data_val['preprocessed_text'].str.contains(money_simbol_list)*1
data_val['suspicious_words'] = data_val['preprocessed_text'].str.contains(suspicious_words)*1
data_val['text_len'] = data_val['preprocessed_text'].apply(lambda x: len(x)) 

data_train.head()

,text,label,text_clean,preprocessed_text,money_mark,suspicious_words,text_len
442,Dear=2C Good day hope fine=2Cdear am writting ...,1,"[dear, good, day, hope, fine, cdear, writting,...","[dear, good, day, hope, fine, cdear, writting,...",NaN,NaN,147
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,1,"[mr, henry, kaborethe, chief, auditor, incharg...","[mr, henry, kaborethe, chief, auditor, incharg...",NaN,NaN,257
971,Will do.,0,[],[],NaN,NaN,0
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,1,"[desk, dr, adamu, ismalerauditing, accounting,...","[desk, dr, adamu, ismalerauditing, accounting,...",NaN,NaN,52
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...",1,"[dear, friend, name, loi, estrada, wife, mr, j...","[dear, friend, name, loi, estrada, wife, mr, j...",NaN,NaN,184

## How would work the Bag of Words with Count Vectorizer concept?

In [147]:
# Bag of Words with CountVectorizer

X_train_text = data_train["preprocessed_text"].apply(lambda tokens: " ".join(tokens))
X_val_text = data_val["preprocessed_text"].apply(lambda tokens: " ".join(tokens))

y_train = data_train["label"]
y_val = data_val["label"]

count_vectorizer = CountVectorizer(
    lowercase=True,
    stop_words="english",
    token_pattern=r"(?u)\b\w\w+\b",
    ngram_range=(1, 1)
)

X_train_bow = count_vectorizer.fit_transform(X_train_text)
X_val_bow = count_vectorizer.transform(X_val_text)

feature_names = count_vectorizer.get_feature_names_out()

print("Train Bag of Words shape:", X_train_bow.shape)
print("Validation Bag of Words shape:", X_val_bow.shape)
print("Number of words in vocabulary:", len(feature_names))
print("First 20 words:", feature_names[:20])

# Create Bag of Words DataFrame
bow_df = pd.DataFrame(
    X_train_bow.toarray(),
    columns=feature_names,
    index=data_train.index
)

bow_df["label"] = y_train.values

# Top 10 words by label
top_10_by_label = []

for label in bow_df["label"].unique():
    label_word_freq = (
        bow_df[bow_df["label"] == label]
        .drop(columns="label")
        .sum()
        .sort_values(ascending=False)
        .head(10)
        .reset_index()
    )

    label_word_freq.columns = ["word", "frequency"]
    label_word_freq["label"] = label

    top_10_by_label.append(label_word_freq)

top_10_by_label_df = pd.concat(top_10_by_label, ignore_index=True)

top_10_by_label_df

Train Bag of Words shape: (800, 27124)
Validation Bag of Words shape: (200, 27124)
Number of words in vocabulary: 27124
First 20 words: ['aa' 'aaa' 'aabeiawaeaambiqaceqedeqh' 'aac' 'aaccount' 'aacute' 'aacw'
 'aae' 'aaecaxeebsexbhjbuqdhcrmimoeifekrobhbcsmzuvavynlrchyknoel'
 'aaegmdbsch' 'aaeh' 'aaevvsghq' 'aafh' 'aaftmjiprqbge' 'aafyb' 'aafyuzt'
 'aagadrk' 'aagcdm' 'aaghhq' 'aagre']

           word  frequency  label
0         money        761      1
1       account        674      1
2          bank        616      1
3          fund        604      1
4      transfer        435      1
5   transaction        435      1
6      business        412      1
7       country        401      1
8          nbsp        387      1
9            mr        384      1
10         work         97      0
11        state         97      0
12          say         96      0
13    president         95      0
14           mr         90      0
15      percent         80      0
16        obama         80      0
17         time         70      0
18           pm         68      0
19     american         61      0

In [148]:
top_10_by_label_df[["label", "word", "frequency"]]

    label         word  frequency
0       1        money        761
1       1      account        674
2       1         bank        616
3       1         fund        604
4       1     transfer        435
5       1  transaction        435
6       1     business        412
7       1      country        401
8       1         nbsp        387
9       1           mr        384
10      0         work         97
11      0        state         97
12      0          say         96
13      0    president         95
14      0           mr         90
15      0      percent         80
16      0        obama         80
17      0         time         70
18      0           pm         68
19      0     american         61

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [149]:
# Your code
from sklearn.feature_extraction.text import TfidfVectorizer

# TF-IDF expects strings, not token lists
X_train_text = data_train["preprocessed_text"].apply(lambda tokens: " ".join(tokens))
X_val_text = data_val["preprocessed_text"].apply(lambda tokens: " ".join(tokens))

# Load / create the vectorizer
tfidf_vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words="english",
    token_pattern=r"(?u)\b\w\w+\b",
    ngram_range=(1, 1)
)

# Vectorize the datasets
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train_text)
X_val_tfidf = tfidf_vectorizer.transform(X_val_text)

# Print shapes
print("Train TF-IDF shape:", X_train_tfidf.shape)
print("Validation TF-IDF shape:", X_val_tfidf.shape)

X_all_text = pd.concat([X_train_text, X_val_text])

X_all_tfidf = tfidf_vectorizer.fit_transform(X_all_text)

print("Full TF-IDF dataset shape:", X_all_tfidf.shape)

Train TF-IDF shape: (800, 27124)
Validation TF-IDF shape: (200, 27124)
Full TF-IDF dataset shape: (1000, 28634)

## And the Train a Classifier?

In [150]:
# Your code
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Classifier
classifier = LogisticRegression(
    max_iter=1000,
    random_state=42
)

classifier.fit(X_train_tfidf, y_train)

y_val_pred = classifier.predict(X_val_tfidf)

print("Validation accuracy:", accuracy_score(y_val, y_val_pred))
print(classification_report(y_val, y_val_pred))

Validation accuracy: 0.98
              precision    recall  f1-score   support

           0       0.97      1.00      0.98       112
           1       1.00      0.95      0.98        88

    accuracy                           0.98       200
   macro avg       0.98      0.98      0.98       200
weighted avg       0.98      0.98      0.98       200

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [151]:
# Final task: compare feature sets with the fixed classifier: MultinomialNB()
import re
import numpy as np
import pandas as pd
from pathlib import Path
from scipy.sparse import csr_matrix, hstack
from IPython.display import display
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

RANDOM_STATE = 42

# Make this cell runnable from either the notebook folder or the project root.
data_dir = Path("../data")
if not (data_dir / "kg_train.csv").exists():
    data_dir = Path("data")

train_full = pd.read_csv(data_dir / "kg_train.csv", encoding="latin-1").fillna("")
test_full = pd.read_csv(data_dir / "kg_test.csv", encoding="latin-1").fillna("")

X = train_full["text"].astype(str)
y = train_full["label"]


def clean_email_text(text):
    text = str(text)
    patterns = [
        (r"<script.*?>.*?</script>", " ", re.DOTALL | re.IGNORECASE),
        (r"<style.*?>.*?</style>", " ", re.DOTALL | re.IGNORECASE),
        (r"<!--.*?-->", " ", re.DOTALL),
        (r"<[^>]+>", " ", 0),
        (r"&nbsp;|&amp;|&lt;|&gt;", " ", re.IGNORECASE),
    ]
    for pattern, replacement, flags in patterns:
        text = re.sub(pattern, replacement, text, flags=flags)
    return re.sub(r"\s+", " ", text).strip().lower()


money_pattern = re.compile(
    r"(\$|\u20ac|\u00a3|\busd\b|\beur\b|\beuro\b|\bdollar\b|\bdollars\b|\bpound\b|\bpounds\b)",
    re.IGNORECASE,
)
suspicious_pattern = re.compile(
    r"\b(free|cheap|sex|money|account|bank|fund|funds|transfer|transaction|win|winner|deposit|password|urgent|confidential|inheritance|beneficiary|claim|prize|million|lottery|investment|business proposal|next of kin)\b",
    re.IGNORECASE,
)
url_pattern = re.compile(r"(https?://|www\.)", re.IGNORECASE)
email_pattern = re.compile(r"\b[\w.-]+@[\w.-]+\.\w+\b", re.IGNORECASE)

EXTRA_FEATURE_NAMES = [
    "money_mark",
    "suspicious_words",
    "text_len_log",
    "digit_count",
    "exclamation_count",
    "url_mark",
    "email_mark",
    "html_mark",
    "upper_ratio",
]


def make_extra_features(texts):
    rows = []
    for text in texts:
        raw = str(text)
        letters = sum(ch.isalpha() for ch in raw)
        rows.append([
            int(bool(money_pattern.search(raw))),
            int(bool(suspicious_pattern.search(raw))),
            np.log1p(len(raw)),  # text_len, log-scaled so it does not dominate word counts
            len(re.findall(r"\d", raw)),
            len(re.findall(r"!", raw)),
            int(bool(url_pattern.search(raw))),
            int(bool(email_pattern.search(raw))),
            int("<" in raw and ">" in raw),
            sum(ch.isupper() for ch in raw) / max(1, letters),
        ])
    return csr_matrix(np.asarray(rows, dtype=float))


def vectorized_features(vectorizer, train_text, valid_text, add_extra_features):
    X_train_vec = vectorizer.fit_transform(train_text)
    X_valid_vec = vectorizer.transform(valid_text)

    if add_extra_features:
        X_train_vec = hstack([X_train_vec, make_extra_features(train_text)]).tocsr()
        X_valid_vec = hstack([X_valid_vec, make_extra_features(valid_text)]).tocsr()

    return X_train_vec, X_valid_vec


feature_sets = [
    {
        "name": "Bag of Words only",
        "vectorizer": lambda: CountVectorizer(
            preprocessor=clean_email_text,
            stop_words="english",
            token_pattern=r"(?u)\b\w\w+\b",
        ),
        "extra": False,
    },
    {
        "name": "TF-IDF only",
        "vectorizer": lambda: TfidfVectorizer(
            preprocessor=clean_email_text,
            stop_words="english",
            token_pattern=r"(?u)\b\w\w+\b",
        ),
        "extra": False,
    },
    {
        "name": "Bag of Words + extra flags",
        "vectorizer": lambda: CountVectorizer(
            preprocessor=clean_email_text,
            stop_words="english",
            token_pattern=r"(?u)\b\w\w+\b",
        ),
        "extra": True,
    },
    {
        "name": "TF-IDF + extra flags",
        "vectorizer": lambda: TfidfVectorizer(
            preprocessor=clean_email_text,
            stop_words="english",
            token_pattern=r"(?u)\b\w\w+\b",
        ),
        "extra": True,
    },
    {
        "name": "Bag of Words 1-2 grams + extra flags",
        "vectorizer": lambda: CountVectorizer(
            preprocessor=clean_email_text,
            stop_words="english",
            token_pattern=r"(?u)\b\w\w+\b",
            ngram_range=(1, 2),
            min_df=2,
        ),
        "extra": True,
    },
    {
        "name": "TF-IDF 1-2 grams only",
        "vectorizer": lambda: TfidfVectorizer(
            preprocessor=clean_email_text,
            stop_words="english",
            token_pattern=r"(?u)\b\w\w+\b",
            ngram_range=(1, 2),
            min_df=2,
        ),
        "extra": False,
    },
]

X_train_text, X_val_text, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=RANDOM_STATE,
    stratify=y,
)

results = []
validation_predictions = {}

for config_id, config in enumerate(feature_sets):
    vectorizer = config["vectorizer"]()
    X_train_vec, X_val_vec = vectorized_features(
        vectorizer,
        X_train_text,
        X_val_text,
        config["extra"],
    )

    classifier = MultinomialNB()  # fixed classifier, default parameters
    classifier.fit(X_train_vec, y_train)
    y_val_pred = classifier.predict(X_val_vec)
    validation_predictions[config_id] = y_val_pred

    results.append({
        "config_id": config_id,
        "feature_set": config["name"],
        "n_features": X_train_vec.shape[1],
        "accuracy": accuracy_score(y_val, y_val_pred),
        "f1_spam": f1_score(y_val, y_val_pred, pos_label=1),
    })

results_df = (
    pd.DataFrame(results)
    .sort_values(["accuracy", "f1_spam"], ascending=False)
    .reset_index(drop=True)
)

display(results_df[["feature_set", "n_features", "accuracy", "f1_spam"]])

best_config_id = int(results_df.loc[0, "config_id"])
best_config = feature_sets[best_config_id]
best_pred = validation_predictions[best_config_id]

print(f"Best feature set: {best_config['name']}")
print("\nConfusion matrix:")
print(confusion_matrix(y_val, best_pred))
print("\nClassification report:")
print(classification_report(y_val, best_pred))

# Fit the selected feature set on all labelled rows, then predict Kaggle test labels.
best_vectorizer = best_config["vectorizer"]()
X_full_vec = best_vectorizer.fit_transform(X)
X_test_vec = best_vectorizer.transform(test_full["text"].astype(str))

if best_config["extra"]:
    X_full_vec = hstack([X_full_vec, make_extra_features(X)]).tocsr()
    X_test_vec = hstack([X_test_vec, make_extra_features(test_full["text"].astype(str))]).tocsr()

final_classifier = MultinomialNB()  # fixed classifier, default parameters
final_classifier.fit(X_full_vec, y)
test_predictions = final_classifier.predict(X_test_vec)

# Most relevant features according to the fitted Naive Bayes log-probability ratio.
feature_names = list(best_vectorizer.get_feature_names_out())
if best_config["extra"]:
    feature_names += EXTRA_FEATURE_NAMES

log_ratio = final_classifier.feature_log_prob_[1] - final_classifier.feature_log_prob_[0]
feature_importance = pd.DataFrame({
    "feature": feature_names,
    "spam_vs_ham_log_ratio": log_ratio,
})

print("\nTop features pushing predictions toward SPAM (label=1):")
display(feature_importance.sort_values("spam_vs_ham_log_ratio", ascending=False).head(20))

print("Top features pushing predictions toward HAM (label=0):")
display(feature_importance.sort_values("spam_vs_ham_log_ratio", ascending=True).head(20))

output_dir = data_dir.parent / "your-code"
if not output_dir.exists():
    output_dir = Path(".")

submission_with_id = pd.DataFrame({
    "Id": np.arange(len(test_predictions)),
    "label": test_predictions,
})
submission_labels_only = pd.DataFrame({"label": test_predictions})

submission_with_id.to_csv(output_dir / "submission.csv", index=False)
submission_labels_only.to_csv(output_dir / "submission_labels_only.csv", index=False)

print(f"\nSaved: {(output_dir / 'submission.csv').resolve()}")
print(f"Saved: {(output_dir / 'submission_labels_only.csv').resolve()}")
print("Prediction distribution:")
print(submission_labels_only["label"].value_counts().sort_index())

                            feature_set  n_features  accuracy   f1_spam
0  Bag of Words 1-2 grams + extra flags       73428  0.991618  0.990234
1            Bag of Words + extra flags       68511  0.989941  0.988350
2                 TF-IDF 1-2 grams only       73419  0.984074  0.981535
3                     Bag of Words only       68502  0.968986  0.964661
4                           TF-IDF only       68502  0.965633  0.961064
5                  TF-IDF + extra flags       68511  0.906119  0.897059

Best feature set: Bag of Words 1-2 grams + extra flags

Confusion matrix:
[[676   1]
 [  9 507]]

Classification report:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       677
           1       1.00      0.98      0.99       516

    accuracy                           0.99      1193
   macro avg       0.99      0.99      0.99      1193
weighted avg       0.99      0.99      0.99      1193


Top features pushing predictions toward SPAM (label=1):

                feature  spam_vs_ham_log_ratio
4758                 2e               8.012840
4795              2e 2e               7.012712
84343       transaction               6.718108
3430                 2c               6.638329
80294               sum               6.186071
39313         foreigner               5.678235
18613       beneficiary               5.357166
90                  000               5.331461
50776               kin               5.315143
6049                2ei               5.280205
75608  security company               5.265279
91               000 00               5.150687
79359    states dollars               5.145615
8217                 5f               4.972068
8218              5f 5f               4.953757
92              000 000               4.836230
84850    transfer money               4.831600
25259   confidentiality               4.812865
56943  million thousand               4.808125
86051         unclaimed               4.766907

Top features pushing predictions toward HAM (label=0):

                      feature  spam_vs_ham_log_ratio
61567                   obama              -7.560657
66694                      pm              -7.315584
1643                     2009              -7.309854
41239                     fyi              -7.033600
18797                benghazi              -6.747936
56                      00 pm              -6.655043
88035                    vote              -6.572046
55921              mcchrystal              -6.421893
89327             white house              -6.334374
88243                  waiver              -6.334374
76207   sensitive information              -6.322104
75878         select benghazi              -6.322104
47233  information redactions              -6.322104
38925                    foia              -6.322104
12363     agreement sensitive              -6.322104
38926             foia waiver              -6.322104
45110            house select              -6.322104
71186         redactions foia              -6.322104
18798           benghazi comm              -6.322104
30253           dept produced              -6.322104

Saved: C:\Users\ranik\IRONHACK\DSML\W7_NLP\D1\lab-natural-language-processing\your-code\submission.csv
Saved: C:\Users\ranik\IRONHACK\DSML\W7_NLP\D1\lab-natural-language-processing\your-code\submission_labels_only.csv
Prediction distribution:
label
0    3379
1    2585
Name: count, dtype: int64