In [42]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [43]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [44]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

                                                  text  label
0    DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                             Will do.      0
2    Nora--Cheryl has emailed dozens of memos about...      0
3    Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                  fyi      0
..                                                 ...    ...
995  So what's the latest? It sounds contradictory ...      0
996  TRANSFER OF 36,759,000.00 MILLION POUNDS TO YO...      1
997  Barb I will call to explain. Are you back in t...      0
998    Yang on travelNot free tonite.May work tomorrow      0
999  sbwhoeopSunday February 21 2010 7:42 PMHShaunH...      0

[1000 rows x 2 columns]

### Let's divide the training and test set into two partitions

In [45]:
# Your code
from sklearn.model_selection import train_test_split

data_train, data_val = train_test_split(data, test_size=0.2, random_state=42, stratify=data['label'])
print(f"Training set: {data_train.shape}")
print(f"Validation set: {data_val.shape}")

Training set: (800, 2)
Validation set: (200, 2)

## Data Preprocessing

In [46]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [47]:
# Your code
import re

def clean_html(text):
    # Remove inline JavaScript/CSS
    text = re.sub(r'<(script|style).*?>.*?</\1>', '', text, flags=re.DOTALL)
    # Remove HTML comments
    text = re.sub(r'<!--.*?-->', '', text, flags=re.DOTALL)
    # Remove remaining HTML tags
    text = re.sub(r'<.*?>', '', text)
    return text

data_train['cleaned_text'] = data_train['text'].apply(clean_html)
data_val['cleaned_text'] = data_val['text'].apply(clean_html)
print(data_train['cleaned_text'].head())

442    Dear=2C Good day hope fine=2Cdear am writting ...
962    FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...
971                                             Will do.
190    FROM THE DESK OF DR.ADAMU  ISMALERAUDITING AND...
551    Dear Friend, My name is LOI C.ESTRADA,The wife...
Name: cleaned_text, dtype: str

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [48]:
# Your code
import re

def preprocess_text(text):
    # Remove all the special characters
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    # Remove numbers (already handled by special chars, but explicit)
    text = re.sub(r'\d+', '', text)
    # Remove all single characters
    text = re.sub(r'\b[a-zA-Z]\b', '', text)
    # Remove single characters from the start
    text = re.sub(r'^[a-zA-Z]\s+', '', text)
    # Substitute multiple spaces with single space
    text = re.sub(r'\s+', ' ', text)
    # Remove prefixed 'b'
    text = re.sub(r'\bb\s+', '', text)
    # Convert to Lowercase
    text = text.lower()
    # Strip leading/trailing whitespace
    text = text.strip()
    return text

data_train['preprocessed_text'] = data_train['cleaned_text'].apply(preprocess_text)
data_val['preprocessed_text'] = data_val['cleaned_text'].apply(preprocess_text)
print(data_train['preprocessed_text'].head())

442    dearc good day hope finecdear am writting this...
962    from mr henry kaborethe chief auditor incharge...
971                                              will do
190    from the desk of dradamu ismalerauditing and a...
551    dear friend my name is loi cestradathe wife of...
Name: preprocessed_text, dtype: str

## Now let's work on removing stopwords
Remove the stopwords.

In [49]:
# Your code
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    return ' '.join([word for word in text.split() if word not in stop_words])

data_train['preprocessed_text'] = data_train['preprocessed_text'].apply(remove_stopwords)
data_val['preprocessed_text'] = data_val['preprocessed_text'].apply(remove_stopwords)
print(data_train['preprocessed_text'].head())

442    dearc good day hope finecdear writting mail du...
962    mr henry kaborethe chief auditor inchargeforei...
971
190    desk dradamu ismalerauditing accounting manage...
551    dear friend name loi cestradathe wife mr josep...
Name: preprocessed_text, dtype: str

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [50]:
# Your code
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatize_text(text):
    return ' '.join([lemmatizer.lemmatize(word) for word in text.split()])

data_train['preprocessed_text'] = data_train['preprocessed_text'].apply(lemmatize_text)
data_val['preprocessed_text'] = data_val['preprocessed_text'].apply(lemmatize_text)
print(data_train['preprocessed_text'].head())

442    dearc good day hope finecdear writting mail du...
962    mr henry kaborethe chief auditor inchargeforei...
971
190    desk dradamu ismalerauditing accounting manage...
551    dear friend name loi cestradathe wife mr josep...
Name: preprocessed_text, dtype: str

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [51]:
# Your code
from sklearn.feature_extraction.text import CountVectorizer

# Get top 10 words in spam and ham messages
spam_texts = data_train[data_train['label'] == 1]['preprocessed_text']
ham_texts = data_train[data_train['label'] == 0]['preprocessed_text']

vectorizer = CountVectorizer()

In [52]:
# Spam top words
spam_counts = vectorizer.fit_transform(spam_texts)
spam_sum = spam_counts.sum(axis=0)
spam_top_idx = spam_sum.argsort()[0, -10:][0, ::-1]
spam_top_words = [(vectorizer.get_feature_names_out()[i], spam_sum[0, i]) for i in spam_top_idx.tolist()[0]]
print("Top 10 SPAM words:", spam_top_words)

Top 10 SPAM words: [('money', np.int64(708)), ('account', np.int64(596)), ('bank', np.int64(571)), ('fund', np.int64(540)), ('business', np.int64(383)), ('transaction', np.int64(327)), ('country', np.int64(319)), ('million', np.int64(305)), ('company', np.int64(299)), ('transfer', np.int64(293))]

In [53]:
# Ham top words
ham_counts = vectorizer.fit_transform(ham_texts)
ham_sum = ham_counts.sum(axis=0)
ham_top_idx = ham_sum.argsort()[0, -10:][0, ::-1]
ham_top_words = [(vectorizer.get_feature_names_out()[i], ham_sum[0, i]) for i in ham_top_idx.tolist()[0]]
print("Top 10 HAM words:", ham_top_words)

Top 10 HAM words: [('would', np.int64(91)), ('president', np.int64(90)), ('percent', np.int64(76)), ('call', np.int64(75)), ('state', np.int64(72)), ('mr', np.int64(70)), ('work', np.int64(70)), ('one', np.int64(62)), ('american', np.int64(60)), ('obama', np.int64(60))]

## Extra features

In [54]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['preprocessed_text'].str.contains(money_simbol_list)*1
data_train['suspicious_words'] = data_train['preprocessed_text'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['preprocessed_text'].apply(lambda x: len(x)) 

data_val['money_mark'] = data_val['preprocessed_text'].str.contains(money_simbol_list)*1
data_val['suspicious_words'] = data_val['preprocessed_text'].str.contains(suspicious_words)*1
data_val['text_len'] = data_val['preprocessed_text'].apply(lambda x: len(x)) 

data_train.head()

,text,label,cleaned_text,preprocessed_text,money_mark,suspicious_words,text_len
442,Dear=2C Good day hope fine=2Cdear am writting ...,1,Dear=2C Good day hope fine=2Cdear am writting ...,dearc good day hope finecdear writting mail du...,1,1,1024
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,1,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,mr henry kaborethe chief auditor inchargeforei...,0,1,1954
971,Will do.,0,Will do.,,0,0,0
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,1,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,desk dradamu ismalerauditing accounting manage...,1,1,390
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...",1,"Dear Friend, My name is LOI C.ESTRADA,The wife...",dear friend name loi cestradathe wife mr josep...,1,1,1507

## How would work the Bag of Words with Count Vectorizer concept?

In [55]:
# Your code
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer()
X_train_bow = count_vectorizer.fit_transform(data_train['preprocessed_text'])
X_val_bow = count_vectorizer.transform(data_val['preprocessed_text'])

print("Bag of Words shape:", X_train_bow.shape)
print("Sample features:", count_vectorizer.get_feature_names_out()[:10])

Bag of Words shape: (800, 17180)
Sample features: ['aac' 'aaclocated' 'aae' 'aag' 'aaronovitchon' 'abacha' 'abachac'
 'abachace' 'abachacthe' 'abachactransferred']

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [56]:
# Your code
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(data_train['preprocessed_text'])
X_val_tfidf = tfidf_vectorizer.transform(data_val['preprocessed_text'])

print("TF-IDF shape:", X_train_tfidf.shape)

TF-IDF shape: (800, 17180)

## And the Train a Classifier?

In [57]:
# Your code
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

model = MultinomialNB()
model.fit(X_train_tfidf, data_train['label'])

y_pred = model.predict(X_val_tfidf)
print("Accuracy:", accuracy_score(data_val['label'], y_pred))
print(classification_report(data_val['label'], y_pred))

Accuracy: 0.945
              precision    recall  f1-score   support

           0       1.00      0.90      0.95       112
           1       0.89      1.00      0.94        88

    accuracy                           0.94       200
   macro avg       0.94      0.95      0.94       200
weighted avg       0.95      0.94      0.95       200

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [58]:
# Your code
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import scipy.sparse as sp

extra_train = data_train[['money_mark', 'suspicious_words', 'text_len']].values
extra_val = data_val[['money_mark', 'suspicious_words', 'text_len']].values

results = {}

### Bag of Words

In [ ]:
model1 = MultinomialNB()
model1.fit(X_train_bow, data_train['label'])
y_pred1 = model1.predict(X_val_bow)
results['BoW only'] = accuracy_score(data_val['label'], y_pred1)

### TF-IDF

In [ ]:
model2 = MultinomialNB()
model2.fit(X_train_tfidf, data_train['label'])
y_pred2 = model2.predict(X_val_tfidf)
results['TF-IDF only'] = accuracy_score(data_val['label'], y_pred2)

### Bag of Words + extra flags

In [ ]:
X_train_bow_extra = sp.hstack([X_train_bow, extra_train])
X_val_bow_extra = sp.hstack([X_val_bow, extra_val])
model3 = MultinomialNB()
model3.fit(X_train_bow_extra, data_train['label'])
y_pred3 = model3.predict(X_val_bow_extra)
results['BoW + extra'] = accuracy_score(data_val['label'], y_pred3)

### TF-IDF + extra flags

In [ ]:
X_train_tfidf_extra = sp.hstack([X_train_tfidf, extra_train])
X_val_tfidf_extra = sp.hstack([X_val_tfidf, extra_val])
model4 = MultinomialNB()
model4.fit(X_train_tfidf_extra, data_train['label'])
y_pred4 = model4.predict(X_val_tfidf_extra)
results['TF-IDF + extra'] = accuracy_score(data_val['label'], y_pred4)

### Results

In [68]:
for name, acc in sorted(results.items(), key=lambda x: x[1], reverse=True):
    print(f"{name:20s} {acc:.3f}")

BoW only             0.965
TF-IDF only          0.945
BoW + extra          0.875
TF-IDF + extra       0.680

In [77]:
best = max(results, key=results.get)
print(f"\n Best {best} with accuracy {results[best]:.3f}")

 Best BoW only with accuracy 0.965