In [1]:
from IPython.display import display, HTML                               ## IPython.core.display does not work anymore
display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer
import regex as re
from sklearn.feature_extraction.text import CountVectorizer
from nltk.stem import WordNetLemmatizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speed up development.

In [3]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

                                                  text  label
0    DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                             Will do.      0
2    Nora--Cheryl has emailed dozens of memos about...      0
3    Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                  fyi      0
..                                                 ...    ...
995  So what's the latest? It sounds contradictory ...      0
996  TRANSFER OF 36,759,000.00 MILLION POUNDS TO YO...      1
997  Barb I will call to explain. Are you back in t...      0
998    Yang on travelNot free tonite.May work tomorrow      0
999  sbwhoeopSunday February 21 2010 7:42 PMHShaunH...      0

[1000 rows x 2 columns]

### Let's divide the training and test set into two partitions

In [5]:
data_train = data.copy()

data_test = data_train.sample(frac=0.25)
data_val = data_test.sample(frac=0.4)

data_train = data_train.drop(data_test.index)
data_test = data_test.drop(data_val.index)

## Data Preprocessing

In [6]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')
from nltk import pos_tag

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [7]:
def java_html_remover(text:str):

    text = re.sub(r"<script.*?>.*?</script>", " ", text, flags=re.DOTALL)

    text = re.sub(r"<style.*?>.*?</style>", " ", text, flags=re.DOTALL)

    text = re.sub(r"<style.*?>.*?</style>", " ", text, flags=re.DOTALL)

    text =  re.sub(r"<.*?>", " ", text)

    return (text)

In [8]:
data_train["preprocessed_text"] = data_train["text"].apply(java_html_remover)
data_test["preprocessed_text"] = data_test["text"].apply(java_html_remover)
data_val["preprocessed_text"] = data_val["text"].apply(java_html_remover)

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [9]:
def generic_cleaner(text:str):

    #a lot of these are redundant but included for completeness

    text = re.sub(r"[^A-Za-z\s]", " ", text)            # removes all non letters and white space   
    text = re.sub(r"^b\s+", "", text)                   # removes the letter be at the beginning of a string
    text = re.sub(r"^[A-Za-z]\s+", "", text)            # removes all 'normal' characters at the beginning of the string
    text = re.sub(r"\b[A-Za-z]\b", " ", text)           # removes all 'normal' isolated single characters
    text = re.sub(r"\d+", " ", text)                    # removes all digits (again, I know this is redundant but has been included to show it is possible)
    text = re.sub(r"\s+", " ", text).strip()            # removes all non single white space, and white space starting and ending the string
    text = text.lower()                                 # lower case
    
    return (text)

In [10]:
data_train["preprocessed_text"] = data_train["preprocessed_text"].apply(generic_cleaner)
data_test["preprocessed_text"] = data_test["preprocessed_text"].apply(generic_cleaner)
data_val["preprocessed_text"] = data_val["preprocessed_text"].apply(generic_cleaner)

## Now let's work on removing stopwords
Remove the stopwords.

In [11]:
def stopword_removal(text):

    stop_words = set(stopwords.words("english"))

    temp = text.split()
    temp = [_ for _ in temp if _ not in stop_words]

    text = " ".join(temp)

    return(text)

In [12]:
data_train["preprocessed_text"] = data_train["preprocessed_text"].apply(stopword_removal)
data_test["preprocessed_text"] = data_test["preprocessed_text"].apply(stopword_removal)
data_val["preprocessed_text"] = data_val["preprocessed_text"].apply(stopword_removal)

In [13]:
data_train

,text,label,preprocessed_text
0,"DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...",1,dear sir strictly private business proposal mi...
1,Will do.,0,
2,Nora--Cheryl has emailed dozens of memos about...,0,nora cheryl emailed dozens memos haiti weekend...
3,Dear Sir=2FMadam=2C I know that this proposal ...,1,dear sir fmadam know proposal might surprise e...
4,fyi,0,fyi
...,...,...,...
995,So what's the latest? It sounds contradictory ...,0,latest sounds contradictory af decide shall ta...
996,"TRANSFER OF 36,759,000.00 MILLION POUNDS TO YO...",1,transfer million pounds youraccount name mr ej...
997,Barb I will call to explain. Are you back in t...,0,barb call explain back country
998,Yang on travelNot free tonite.May work tomorrow,0,yang travelnot free tonite may work tomorrow
999,sbwhoeopSunday February 21 2010 7:42 PMHShaunH...,0,sbwhoeopsunday february pmhshaunh talked shaun...

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [14]:
wordnet_lemma  = WordNetLemmatizer()

In [15]:
def lemmatiser(text):

    
    temp = text.split()
    lemmatised = [wordnet_lemma.lemmatize(_, pos="n") for _ in temp]

    return(" ".join(lemmatised))

In [16]:
data_train["preprocessed_text"] = data_train["preprocessed_text"].apply(lemmatiser)
data_train["preprocessed_text"] = data_train["preprocessed_text"].apply(lemmatiser)
data_train["preprocessed_text"] = data_train["preprocessed_text"].apply(lemmatiser)

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [17]:
vectoriser = CountVectorizer(max_features=2000)

X_train_bow = vectoriser.fit_transform(data_train["preprocessed_text"])       
X_test_bow = vectoriser.transform(data_test["preprocessed_text"])            # transform only to avoid leakage
X_val_bow = vectoriser.transform(data_val["preprocessed_text"])              # transform only to avoid leakage

In [18]:

def top_words_by_label(df, bow_matrix, vectoriser, ham_spam_code, top_n=10):
    
    indices = df["label"] == ham_spam_code

    word_counts = bow_matrix[indices].sum(axis=0).A1

    vocab = vectoriser.get_feature_names_out()
    
    freq = pd.Series(word_counts, index=vocab)
    
    return freq.sort_values(ascending=False).head(top_n)

In [19]:
top_10_train_ham = top_words_by_label(data_train, X_train_bow, vectoriser, 0)
top_10_test_ham = top_words_by_label(data_test, X_test_bow, vectoriser, 0)
top_10_val_ham = top_words_by_label(data_val, X_val_bow, vectoriser, 0)

top_10_train_spam = top_words_by_label(data_train, X_train_bow, vectoriser, 1)
top_10_test_spam = top_words_by_label(data_test, X_test_bow, vectoriser, 1)
top_10_val_spam = top_words_by_label(data_val, X_val_bow, vectoriser, 1)

print(f"top_10_train_ham:\n{top_10_train_ham}")
print(f"\ntop_10_test_ham:\n{top_10_test_ham}")
print(f"\ntop_10_val_ham:\n{top_10_val_ham}")

print(" - - - - - -")

print(f"\ntop_10_train_spam:\n{top_10_train_spam}")
print(f"\ntop_10_test_spam:\n{top_10_test_spam}")
print(f"\ntop_10_val_spam:\n{top_10_val_spam}")

top_10_train_ham:
state        110
would         98
pm            92
mr            90
president     86
time          86
call          79
obama         77
percent       72
work          69
dtype: int64

top_10_test_ham:
pm            34
state         18
department    12
arrive        11
depart        10
secretary     10
airport       10
meeting       10
route          9
fyi            9
dtype: int64

top_10_val_ham:
iran         11
china        10
doc          10
percent       9
middle        9
president     8
oil           8
east          7
strategic     7
press         7
dtype: int64
 - - - - - -

top_10_train_spam:
money          747
account        696
bank           606
fund           597
transaction    446
business       386
mr             375
country        370
million        340
nbsp           336
dtype: int64

top_10_test_spam:
money          155
account        127
bank           119
nbsp            88
business        84
country         82
transfer        69
mr              64
million         63
transaction     62
dtype: int64

top_10_val_spam:
money          85
bank           74
account        69
country        54
fund           53
nbsp           51
million        49
transfer       47
business       44
transaction    42
dtype: int64

## Extra features

In [20]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['preprocessed_text'].str.contains(money_simbol_list)*1
data_train['suspicious_words'] = data_train['preprocessed_text'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['preprocessed_text'].apply(lambda x: len(x)) 

data_val['money_mark'] = data_val['preprocessed_text'].str.contains(money_simbol_list)*1
data_val['suspicious_words'] = data_val['preprocessed_text'].str.contains(suspicious_words)*1
data_val['text_len'] = data_val['preprocessed_text'].apply(lambda x: len(x)) 

data_train.head()

,text,label,preprocessed_text,money_mark,suspicious_words,text_len
0,"DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...",1,dear sir strictly private business proposal mi...,1,1,1493
1,Will do.,0,,0,0,0
2,Nora--Cheryl has emailed dozens of memos about...,0,nora cheryl emailed dozen memo haiti weekend p...,0,0,111
3,Dear Sir=2FMadam=2C I know that this proposal ...,1,dear sir fmadam know proposal might surprise e...,1,1,1346
4,fyi,0,fyi,0,0,3

## How would work the Bag of Words with Count Vectorizer concept?

In [21]:
vectoriser = CountVectorizer(max_features=2000)

X_train_bow = vectoriser.fit_transform(data_train["preprocessed_text"])       
X_test_bow = vectoriser.transform(data_test["preprocessed_text"])            # transform only to avoid leakage
X_val_bow = vectoriser.transform(data_val["preprocessed_text"])              # transform only to avoid leakage

In [22]:

def top_words_by_label(df, bow_matrix, vectoriser, ham_spam_code, top_n=10):
    
    indices = df["label"] == ham_spam_code

    word_counts = bow_matrix[indices].sum(axis=0).A1

    vocab = vectoriser.get_feature_names_out()
    
    freq = pd.Series(word_counts, index=vocab)
    
    return freq.sort_values(ascending=False).head(top_n)

In [23]:
top_10_train_ham = top_words_by_label(data_train, X_train_bow, vectoriser, 0)
top_10_test_ham = top_words_by_label(data_test, X_test_bow, vectoriser, 0)
top_10_val_ham = top_words_by_label(data_val, X_val_bow, vectoriser, 0)

top_10_train_spam = top_words_by_label(data_train, X_train_bow, vectoriser, 1)
top_10_test_spam = top_words_by_label(data_test, X_test_bow, vectoriser, 1)
top_10_val_spam = top_words_by_label(data_val, X_val_bow, vectoriser, 1)

print(f"top_10_train_ham:\n{top_10_train_ham}")
print(f"\ntop_10_test_ham:\n{top_10_test_ham}")
print(f"\ntop_10_val_ham:\n{top_10_val_ham}")

print(" - - - - - -")

print(f"\ntop_10_train_spam:\n{top_10_train_spam}")
print(f"\ntop_10_test_spam:\n{top_10_test_spam}")
print(f"\ntop_10_val_spam:\n{top_10_val_spam}")

top_10_train_ham:
state        110
would         98
pm            92
mr            90
president     86
time          86
call          79
obama         77
percent       72
work          69
dtype: int64

top_10_test_ham:
pm            34
state         18
department    12
arrive        11
depart        10
secretary     10
airport       10
meeting       10
route          9
fyi            9
dtype: int64

top_10_val_ham:
iran         11
china        10
doc          10
percent       9
middle        9
president     8
oil           8
east          7
strategic     7
press         7
dtype: int64
 - - - - - -

top_10_train_spam:
money          747
account        696
bank           606
fund           597
transaction    446
business       386
mr             375
country        370
million        340
nbsp           336
dtype: int64

top_10_test_spam:
money          155
account        127
bank           119
nbsp            88
business        84
country         82
transfer        69
mr              64
million         63
transaction     62
dtype: int64

top_10_val_spam:
money          85
bank           74
account        69
country        54
fund           53
nbsp           51
million        49
transfer       47
business       44
transaction    42
dtype: int64

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [24]:
def tf_idf_vectoriser(text):

    vectoriser = TfidfVectorizer()

    tfidf_matrix = vectoriser.fit_transform(text)

    return(tfidf_matrix)

In [25]:
tf_idf_vectoriser(data_train["preprocessed_text"]).shape

(750, 27050)

## And the Train a Classifier?

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [27]:
y_train = data_train["label"]
y_test = data_test["label"]
y_val = data_val["label"]

model = LogisticRegression(max_iter=200)
model.fit(X_train_bow, y_train)

y_train_pred = model.predict(X_train_bow)
y_test_pred = model.predict(X_test_bow)

print("Train Accuracy:", accuracy_score(y_train, y_train_pred))
print("Test Accuracy:", accuracy_score(y_test, y_test_pred))

Train Accuracy: 0.9906666666666667
Test Accuracy: 0.9666666666666667