In [2]:
from IPython.display import display, HTML

In [6]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

ImportError: cannot import name 'display' from 'IPython.core.display' (C:\Users\traik\AppData\Roaming\Python\Python311\site-packages\IPython\core\display.py)

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [5]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv(r"C:\Users\traik\Desktop\ML_Bootcamp\Week7\Day1\lab-natural-language-processing\data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

In [8]:
data.columns

Index(['text', 'label'], dtype='object')

### Let's divide the training and test set into two partitions

In [9]:
# Your code
X = data["text"]
y = data["label"]

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_tran, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

## Data Preprocessing

In [7]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

In [12]:
data.head()

                                                text  label
0  DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                           Will do.      0
2  Nora--Cheryl has emailed dozens of memos about...      0
3  Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                fyi      0

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [13]:
import re

In [14]:
# Your code
import re

data["clean_text"] = data["text"]

# 1. Remove JS and CSS
data["clean_text"] = data["clean_text"].str.replace(r"<script.*?>.*?</script>", "", regex=True, flags=re.DOTALL)
data["clean_text"] = data["clean_text"].str.replace(r"<style.*?>.*?</style>", "", regex=True, flags=re.DOTALL)

# 2. Remove comments
data["clean_text"] = data["clean_text"].str.replace(r"<!--.*?-->", "", regex=True, flags=re.DOTALL)

# 3. Remove tags
data["clean_text"] = data["clean_text"].str.replace(r"<[^>]+>", " ", regex=True)

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [16]:
# Your code

# Remove special characters
data["clean_text"] = data["clean_text"].apply(
    lambda x: re.sub(r"[^A-Za-z\s]", " ", x)
)

# Remove numbers
data["clean_text"] = data["clean_text"].apply(
    lambda x: re.sub(r"\d+", " ", x)
)

# Remove all single characters
data["clean_text"] = data["clean_text"].apply(
    lambda x: re.sub(r"\s+[A-Za-z]\s+", " ", x)
)

# Remove single characters at the start
data["clean_text"] = data["clean_text"].apply(
    lambda x: re.sub(r"^[A-Za-z]\s+", "", x)
)

# Replace multiple spaces
data["clean_text"] = data["clean_text"].apply(
    lambda x: re.sub(r"\s+", " ", x)
)

# Remove prefixed b'
data["clean_text"] = data["clean_text"].apply(
    lambda x: re.sub(r"^b\'|^b\"", "", x)
)

# Lowercase (already used in notebooks)
data["clean_text"] = data["clean_text"].str.lower()

## Now let's work on removing stopwords
Remove the stopwords.

In [17]:
# Your code
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

data["clean_text"] = data["clean_text"].apply(
    lambda x: " ".join([word for word in x.split() if word not in stop_words])
)

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [18]:
# Your code
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [19]:
data["clean_text"] = data["clean_text"].apply(
    lambda x: " ".join([lemmatizer.lemmatize(word) for word in x.split()])
)

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [20]:
# Your code
from collections import Counter

In [21]:
ham_texts = data[data["label"]==0]["clean_text"]

In [22]:
spam_texts = data[data["label"]==1]["clean_text"]

In [23]:
ham_words =" ".join(ham_texts).split()

In [24]:
spam_words = " ".join(spam_texts).split()

In [25]:
ham_freq = Counter(ham_words)
spam_freq = Counter(spam_words)

In [27]:
ham_sorted = sorted(ham_freq.items(), key=lambda x: x[1], reverse = True)
spam_sorted = sorted(spam_freq.items(), key=lambda x: x[1], reverse=True)

In [28]:
top_10_ham = ham_sorted[:10]
top_10_spam = spam_sorted[:10]

In [29]:
print("Top 10 HAM words:", top_10_ham)
print("Top 10 SPAM words:", top_10_spam)

Top 10 HAM words: [('state', 136), ('pm', 127), ('would', 107), ('president', 99), ('time', 95), ('call', 94), ('mr', 91), ('obama', 84), ('percent', 81), ('secretary', 79)]
Top 10 SPAM words: [('money', 987), ('account', 899), ('bank', 801), ('fund', 782), ('u', 738), ('transaction', 555), ('business', 514), ('country', 513), ('mr', 490), ('nbsp', 475)]

## Extra features

In [33]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data['money_mark'] = data['clean_text'].str.contains(money_simbol_list)*1
data['suspicious_words'] = data['clean_text'].str.contains(suspicious_words)*1
data['text_len'] = data['clean_text'].apply(lambda x: len(x)) 


data.head()

,text,label,clean_text,money_mark,suspicious_words,text_len
0,"DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...",1,dear sir strictly private business proposal mi...,1,1,1493
1,Will do.,0,,0,0,0
2,Nora--Cheryl has emailed dozens of memos about...,0,nora cheryl emailed dozen memo haiti weekend p...,0,0,111
3,Dear Sir=2FMadam=2C I know that this proposal ...,1,dear sir fmadam know proposal might surprise e...,1,1,1346
4,fyi,0,fyi,0,0,3

## How would work the Bag of Words with Count Vectorizer concept?

In [34]:
# Your code
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(data['clean_text'])

print("Vocabulary size:", len(vectorizer.vocabulary_))
print("Sample feature names:", list(vectorizer.vocabulary_.keys())[:10])

X.toarray()[:5]   # show first 5 rows as dense array

Vocabulary size: 29765
Sample feature names: ['dear', 'sir', 'strictly', 'private', 'business', 'proposal', 'mike', 'chukwu', 'manager', 'bill']

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5, 29765))

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [35]:
# Your code
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)  # optional limit, speeds up training

X_tfidf = tfidf.fit_transform(data["clean_text"])

print("TF-IDF matrix shape:", X_tfidf.shape)
print("Example TF-IDF features:", list(tfidf.vocabulary_.keys())[:10])

TF-IDF matrix shape: (1000, 5000)
Example TF-IDF features: ['dear', 'sir', 'strictly', 'private', 'business', 'proposal', 'mike', 'manager', 'bill', 'exchange']

## And the Train a Classifier?

In [36]:
# Your code
from sklearn.model_selection import train_test_split

X = data["clean_text"]
y = data["label"]

X_train_raw, X_test_raw, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [37]:



X_train = tfidf.fit_transform(X_train_raw)
X_test = tfidf.transform(X_test_raw)

In [38]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()
clf.fit(X_train, y_train)

LogisticRegression()

In [39]:
y_pred = clf.predict(X_test)
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.985

Confusion Matrix:
 [[112   0]
 [  3  85]]

Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.99       112
           1       1.00      0.97      0.98        88

    accuracy                           0.98       200
   macro avg       0.99      0.98      0.98       200
weighted avg       0.99      0.98      0.98       200

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [ ]:
# Your code