In [1]:
from IPython.display import display, HTML

display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [3]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

In [8]:
data.head(10)

                                                text  label
0  DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                           Will do.      0
2  Nora--Cheryl has emailed dozens of memos about...      0
3  Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                fyi      0
5  sure -- bottom line - you need a special secur...      0
6  Dear Sir,I am Engr. Ugo Nzego with the Enginee...      1
7  Abedin Huma <AbedinH@state.gov>Saturday Novemb...      0
8  There is an Oct 16th George Marshall event at ...      0
9  <P>1 25% for you as the account owner <BR>2 65...      1

### Let's divide the training and test set into two partitions

In [4]:
# Your code
from sklearn.model_selection import train_test_split

data_train, data_val = train_test_split(
    data,
    test_size=0.2,
    random_state=42,
    stratify=data["label"]
)

data_train = data_train.copy()
data_val = data_val.copy()

print(data_train.shape)
print(data_val.shape)
print(data_train["label"].value_counts(normalize=True))

(800, 2)
(200, 2)
label
0    0.5575
1    0.4425
Name: proportion, dtype: float64

## Data Preprocessing

In [5]:
import string
from nltk.corpus import stopwords

print(string.punctuation)
print(stopwords.words("english")[100:110])

from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')
stop_words = set(stopwords.words("english"))

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [6]:
# Your code
import re

def remove_html(text):
    text = str(text)

    text = re.sub(r"<script.*?>.*?</script>", " ", text, flags=re.DOTALL | re.IGNORECASE)
    text = re.sub(r"<style.*?>.*?</style>", " ", text, flags=re.DOTALL | re.IGNORECASE)
    text = re.sub(r"<!--.*?-->", " ", text, flags=re.DOTALL)
    text = re.sub(r"<[^>]+>", " ", text)

    return text

data_train["clean_text"] = data_train["text"].apply(remove_html)
data_val["clean_text"] = data_val["text"].apply(remove_html)

data_train[["text", "clean_text"]].head()

,text,clean_text
442,Dear=2C Good day hope fine=2Cdear am writting ...,Dear=2C Good day hope fine=2Cdear am writting ...
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...
971,Will do.,Will do.
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...","Dear Friend, My name is LOI C.ESTRADA,The wife..."

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [9]:
# Your code
def normalize_text(text):
    text = str(text)

    text = re.sub(r"[^a-zA-Z\s]", " ", text)
    text = re.sub(r"\s+[a-zA-Z]\s+", " ", text)
    text = re.sub(r"^[a-zA-Z]\s+", " ", text)
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"^b\s+", "", text)

    return text.lower().strip()

data_train["normalized_text"] = data_train["clean_text"].apply(normalize_text)
data_val["normalized_text"] = data_val["clean_text"].apply(normalize_text)

data_train[["clean_text", "normalized_text"]].head()

,clean_text,normalized_text
442,Dear=2C Good day hope fine=2Cdear am writting ...,dear good day hope fine cdear am writting this...
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,from mr henry kaborethe chief auditor incharge...
971,Will do.,will do
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,from the desk of dr adamu ismalerauditing and ...
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...",dear friend my name is loi estrada the wife of...

## Now let's work on removing stopwords
Remove the stopwords.

In [10]:
# Your code

def remove_stopwords(text):
    words = text.split()
    words = [word for word in words if word not in stop_words]
    return " ".join(words)

data_train["without_stopwords"] = data_train["normalized_text"].apply(remove_stopwords)
data_val["without_stopwords"] = data_val["normalized_text"].apply(remove_stopwords)

data_train[["normalized_text", "without_stopwords"]].head()

,normalized_text,without_stopwords
442,dear good day hope fine cdear am writting this...,dear good day hope fine cdear writting mail du...
962,from mr henry kaborethe chief auditor incharge...,mr henry kaborethe chief auditor inchargeforei...
971,will do,
190,from the desk of dr adamu ismalerauditing and ...,desk dr adamu ismalerauditing accounting manag...
551,dear friend my name is loi estrada the wife of...,dear friend name loi estrada wife mr josephest...

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [11]:
# Your code
import nltk

nltk.download("wordnet")
nltk.download("averaged_perceptron_tagger_eng")


from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
from nltk import pos_tag

lemmatizer = WordNetLemmatizer()

def get_wordnet_pos(tag):
    if tag.startswith("J"):
        return wordnet.ADJ
    elif tag.startswith("V"):
        return wordnet.VERB
    elif tag.startswith("N"):
        return wordnet.NOUN
    elif tag.startswith("R"):
        return wordnet.ADV
    else:
        return wordnet.NOUN

def lemmatize_text(text):
    words = text.split()
    tagged_words = pos_tag(words)

    lemmatized_words = [
        lemmatizer.lemmatize(word, get_wordnet_pos(tag))
        for word, tag in tagged_words
    ]

    return " ".join(lemmatized_words)

data_train["preprocessed_text"] = data_train["without_stopwords"].apply(lemmatize_text)
data_val["preprocessed_text"] = data_val["without_stopwords"].apply(lemmatize_text)

data_train[["without_stopwords", "preprocessed_text"]].head()

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/basstianlopez/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /Users/basstianlopez/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!

,without_stopwords,preprocessed_text
442,dear good day hope fine cdear writting mail du...,dear good day hope fine cdear writting mail du...
962,mr henry kaborethe chief auditor inchargeforei...,mr henry kaborethe chief auditor inchargeforei...
971,,
190,desk dr adamu ismalerauditing accounting manag...,desk dr adamu ismalerauditing accounting manag...
551,dear friend name loi estrada wife mr josephest...,dear friend name loi estrada wife mr josephest...

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [12]:
# Your code

from collections import Counter

def get_top_words(df, label_value, n=10):
    words = " ".join(df.loc[df["label"] == label_value, "preprocessed_text"]).split()
    return pd.DataFrame(Counter(words).most_common(n), columns=["word", "count"])

top_ham = get_top_words(data_train, 0, 10)
top_spam = get_top_words(data_train, 1, 10)

display(top_ham)
display(top_spam)

        word  count
0       work     98
1      state     97
2        say     96
3  president     95
4       call     94
5      would     92
6         mr     89
7        get     81
8      obama     80
9    percent     80

          word  count
0        money    761
1      account    683
2         bank    635
3            u    631
4         fund    606
5            e    523
6  transaction    435
7     transfer    431
8     business    412
9      country    401

## Extra features

In [13]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['preprocessed_text'].str.contains(money_simbol_list)*1
data_train['suspicious_words'] = data_train['preprocessed_text'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['preprocessed_text'].apply(lambda x: len(x)) 

data_val['money_mark'] = data_val['preprocessed_text'].str.contains(money_simbol_list)*1
data_val['suspicious_words'] = data_val['preprocessed_text'].str.contains(suspicious_words)*1
data_val['text_len'] = data_val['preprocessed_text'].apply(lambda x: len(x)) 

data_train.head()

,text,label,clean_text,normalized_text,without_stopwords,preprocessed_text,money_mark,suspicious_words,text_len
442,Dear=2C Good day hope fine=2Cdear am writting ...,1,Dear=2C Good day hope fine=2Cdear am writting ...,dear good day hope fine cdear am writting this...,dear good day hope fine cdear writting mail du...,dear good day hope fine cdear writting mail du...,1,1,982
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,1,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,from mr henry kaborethe chief auditor incharge...,mr henry kaborethe chief auditor inchargeforei...,mr henry kaborethe chief auditor inchargeforei...,0,1,1908
971,Will do.,0,Will do.,will do,,,0,0,0
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,1,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,from the desk of dr adamu ismalerauditing and ...,desk dr adamu ismalerauditing accounting manag...,desk dr adamu ismalerauditing accounting manag...,1,1,374
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...",1,"Dear Friend, My name is LOI C.ESTRADA,The wife...",dear friend my name is loi estrada the wife of...,dear friend name loi estrada wife mr josephest...,dear friend name loi estrada wife mr josephest...,1,1,1452

## How would work the Bag of Words with Count Vectorizer concept?

In [14]:
# Your code
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer = CountVectorizer(max_features=5000)

X_train_bow = count_vectorizer.fit_transform(data_train["preprocessed_text"])
X_val_bow = count_vectorizer.transform(data_val["preprocessed_text"])

print(X_train_bow.shape)
print(X_val_bow.shape)

count_vectorizer.get_feature_names_out()[:20]

(800, 5000)
(200, 5000)

array(['aa', 'aal', 'ab', 'abacha', 'abandon', 'abedin', 'abidjan',
       'abilateral', 'ability', 'able', 'abm', 'abn', 'aboard', 'abroad',
       'absa', 'absence', 'absolute', 'absoluteconfidentiality',
       'absolutely', 'abtf'], dtype=object)

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [15]:
# Your code


tfidf_vectorizer = TfidfVectorizer(max_features=5000)

X_train_tfidf = tfidf_vectorizer.fit_transform(data_train["preprocessed_text"])
X_val_tfidf = tfidf_vectorizer.transform(data_val["preprocessed_text"])

print(X_train_tfidf.shape)
print(X_val_tfidf.shape)

tfidf_vectorizer.get_feature_names_out()[:20]

(800, 5000)
(200, 5000)

array(['aa', 'aal', 'ab', 'abacha', 'abandon', 'abedin', 'abidjan',
       'abilateral', 'ability', 'able', 'abm', 'abn', 'aboard', 'abroad',
       'absa', 'absence', 'absolute', 'absoluteconfidentiality',
       'absolutely', 'abtf'], dtype=object)

## And the Train a Classifier?

In [16]:
# Your code


from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

model = MultinomialNB()

model.fit(X_train_tfidf, data_train["label"])

y_pred = model.predict(X_val_tfidf)

print("Accuracy:", accuracy_score(data_val["label"], y_pred))
print(confusion_matrix(data_val["label"], y_pred))
print(classification_report(data_val["label"], y_pred))

Accuracy: 0.985
[[109   3]
 [  0  88]]
              precision    recall  f1-score   support

           0       1.00      0.97      0.99       112
           1       0.97      1.00      0.98        88

    accuracy                           0.98       200
   macro avg       0.98      0.99      0.98       200
weighted avg       0.99      0.98      0.99       200

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [18]:
# Your code

from scipy.sparse import hstack, csr_matrix

extra_features = ["money_mark", "suspicious_words", "text_len"]

X_train_extra = csr_matrix(data_train[extra_features].values)
X_val_extra = csr_matrix(data_val[extra_features].values)

experiments = {
    "Bag of Words only": (X_train_bow, X_val_bow),
    "TF-IDF only": (X_train_tfidf, X_val_tfidf),
    "Bag of Words + extra features": (
        hstack([X_train_bow, X_train_extra]),
        hstack([X_val_bow, X_val_extra])
    ),
    "TF-IDF + extra features": (
        hstack([X_train_tfidf, X_train_extra]),
        hstack([X_val_tfidf, X_val_extra])
    )
}

results = []

for name, (X_train_exp, X_val_exp) in experiments.items():
    model = MultinomialNB()
    model.fit(X_train_exp, data_train["label"])

    y_pred = model.predict(X_val_exp)

    results.append({
        "experiment": name,
        "accuracy": accuracy_score(data_val["label"], y_pred)
    })

results_df = pd.DataFrame(results).sort_values("accuracy", ascending=False)
results_df

                      experiment  accuracy
1                    TF-IDF only     0.985
0              Bag of Words only     0.980
2  Bag of Words + extra features     0.975
3        TF-IDF + extra features     0.910

In [19]:
print(classification_report(data_val["label"], y_pred))

              precision    recall  f1-score   support

           0       0.99      0.85      0.91       112
           1       0.84      0.99      0.91        88

    accuracy                           0.91       200
   macro avg       0.91      0.92      0.91       200
weighted avg       0.92      0.91      0.91       200

The best performing representation was TF-IDF without additional manual features, reaching an accuracy of 0.985. This suggests that the textual content alone contains enough discriminative information to separate fraudulent and non-fraudulent messages. Bag of Words also performed well, but TF-IDF slightly improved the results by weighting more informative terms. Adding extra features such as money symbols, suspicious words, and text length did not improve performance and even reduced accuracy, especially when combined with TF-IDF. Therefore, the recommended approach is to use TF-IDF features with the default MultinomialNB classifier