In [61]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [62]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

### Note from Ana before starting: 
* do test train split for the train dataset
* check RegEx website
* data cleaning is heavy 
* save variables when you do each step
* for classifier you can pick any, LogisticRegression...etc
* Use the model to fit the X_train clasifier..etc
* 0 is HAM, 1 is SPAM

In [63]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("C:/Users/anmnu/DSML/Week7/Day31/Lab/lab-natural-language-processing/data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

### Let's divide the training and test set into two partitions

In [64]:
# Your code
from sklearn.model_selection import train_test_split
data_train, data_val = train_test_split(data, test_size = 0.2, random_state = 42, stratify = data['label'])

# Here I am making the test size 20% of the dataset

## Data Preprocessing

In [65]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [66]:
import re # regular expressions

# I want to first create a copy column without modifying the original
# Also, it will be a good way to compare before and after  
data['clean_text'] = data['text']

In [67]:
# Your code
# Remove inline JavaScript/CSS
# So we want to remove things with <script>...</script> or <style>...</style>

data['clean_text'] = data['clean_text'].apply(lambda x: re.sub(r'<script.*?>.*?</script>', '', str(x), flags=re.DOTALL))
data['clean_text'] = data['clean_text'].apply(lambda x: re.sub(r'<style.*?>.*?</style>', '', str(x), flags=re.DOTALL))

In [68]:
# Removing html comments
data['clean_text'] = data['clean_text'].apply(lambda x: re.sub(r'<!--.*?-->', '', str(x), flags=re.DOTALL))

In [69]:
# removing remaining tags 
data['clean_text'] = data['clean_text'].apply(lambda x: re.sub(r'<[^>]+>', '', str(x)))

In [ ]:
data[['text', 'clean_text']].head(30)

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

In [70]:
# Your code

# Removing special characters
data['clean_text'] = data['clean_text'].apply(lambda x: re.sub(r'[^a-zA-Z]', ' ', str(x)))

# Removing numbers
data['clean_text'] = data['clean_text'].apply(lambda x: re.sub(r'\d+', '', str(x)))

# Removing all single characters 
data['clean_text'] = data['clean_text'].apply(lambda x: re.sub(r'\b[a-zA-Z]\b', '', str(x)))

# Removing single characters from the start 
data['clean_text'] = data['clean_text'].apply(lambda x: re.sub(r'^\s*[a-zA-Z]\s+', '', str(x)))

# Substituting multiple spaces with single space 
data['clean_text'] = data['clean_text'].apply(lambda x: re.sub(r'\s+', ' ', str(x)))

# Removing prefixed 'b'
data['clean_text'] = data['clean_text'].apply(lambda x: re.sub(r'^b\s+', '', str(x)))

# Converting to lower case 
data['clean_text'] = data['clean_text'].str.lower()

In [ ]:
# Sanity check 
data[['text', 'clean_text']].head(50)

## Now let's work on removing stopwords
Remove the stopwords.

In [71]:
# Your code
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

data['clean_text'] = data['clean_text'].apply(lambda x: ' '.join(
        word for word in x.split()
        if word not in stop_words))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\anmnu\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
# Sanity check 
data[['text', 'clean_text']].head(50)

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [72]:
# Your code
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

data['clean_text'] = data['clean_text'].apply(lambda x: ' '.join(
        lemmatizer.lemmatize(word)
        for word in x.split()
    ))

In [ ]:
# Sanity check 
data[['text', 'clean_text']].head(50)

In [73]:
# now I am replacing text with clean_text after data cleaning
data['text'] = data['clean_text']

In [74]:
# Sanity check
data

,text,label,clean_text
0,dear sir strictly private business proposal mi...,1,dear sir strictly private business proposal mi...
1,,0,
2,nora cheryl emailed dozen memo haiti weekend p...,0,nora cheryl emailed dozen memo haiti weekend p...
3,dear sir fmadam know proposal might surprise e...,1,dear sir fmadam know proposal might surprise e...
4,fyi,0,fyi
...,...,...,...
995,latest sound contradictory af decide shall tak...,0,latest sound contradictory af decide shall tak...
996,transfer million pound youraccount name mr eji...,1,transfer million pound youraccount name mr eji...
997,barb call explain back country,0,barb call explain back country
998,yang travelnot free tonite may work tomorrow,0,yang travelnot free tonite may work tomorrow
999,sbwhoeopsunday february pmhshaunh talked shaun...,0,sbwhoeopsunday february pmhshaunh talked shaun...

In [75]:
# dropping the clean_text column
data.drop(columns = ['clean_text'], inplace = True)

In [76]:
# Sanity check 
data

                                                  text  label
0    dear sir strictly private business proposal mi...      1
1                                                           0
2    nora cheryl emailed dozen memo haiti weekend p...      0
3    dear sir fmadam know proposal might surprise e...      1
4                                                  fyi      0
..                                                 ...    ...
995  latest sound contradictory af decide shall tak...      0
996  transfer million pound youraccount name mr eji...      1
997                     barb call explain back country      0
998       yang travelnot free tonite may work tomorrow      0
999  sbwhoeopsunday february pmhshaunh talked shaun...      0

[1000 rows x 2 columns]

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [81]:
# Your code
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [82]:
# since we did data cleaning, we had to do this again 

data_train, data_val = train_test_split(data, test_size = 0.2, random_state = 42, stratify = data['label'])

In [83]:
X_train_bow = vectorizer.fit_transform(data_train['text'])
X_val_bow = vectorizer.transform(data_val['text'])
y_train = data_train['label']
y_val = data_val['label']

In [84]:
words = vectorizer.get_feature_names_out()
word_counts = X_train_bow.toarray().sum(axis=0)

bow_df = pd.DataFrame({
    'word': words,
    'count': word_counts
})

In [85]:
top10 = bow_df.sort_values(by='count', ascending=False).head(10)
print(top10)

              word  count
15195        money    762
232        account    676
2587          bank    623
8736          fund    601
15324           mr    473
4999       country    444
3475      business    439
23414  transaction    432
15729         nbsp    387
14981      million    371

## Extra features

In [87]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_symbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['text'].str.contains(money_symbol_list)*1
data_train['suspicious_words'] = data_train['text'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['text'].apply(lambda x: len(x)) 

data_val['money_mark'] = data_val['text'].str.contains(money_symbol_list)*1
data_val['suspicious_words'] = data_val['text'].str.contains(suspicious_words)*1
data_val['text_len'] = data_val['text'].apply(lambda x: len(x)) 

data_train.head()

,text,label,money_mark,suspicious_words,text_len
442,dear good day hope fine cdear writting mail du...,1,1,1,998
962,mr henry kaborethe chief auditor inchargeforei...,1,0,1,1946
971,,0,0,0,0
190,desk dr adamu ismalerauditing accounting manag...,1,1,1,383
551,dear friend name loi estrada wife mr josephest...,1,1,1,1475

## How would work the Bag of Words with Count Vectorizer concept?

In [ ]:
# Your code
# How does Bag of Words work using CountVectorizer? 

# 1. CountVectorizer scans all training texts first then converts sentences into vectors
# 2. CountVectorizer learns the vocabulary using fit() and converts the text into a numerical count matrix using transform()
# 3. We got the numerical sparse matrix
# 4. Also, the word order does NOT matter here. 
# 5. Each unique word becomes a feature/column in the matrix

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [88]:
# Your code
from sklearn.feature_extraction.text import TfidfVectorizer

# Load vectorizer
vectorizer = TfidfVectorizer()

# Vectorize all dataset
X_train_tfidf = vectorizer.fit_transform(data_train['text'])
X_val_tfidf = vectorizer.transform(data_val['text'])

# Print shape of vectorized dataset
print("Training TF-IDF Shape:", X_train_tfidf.shape)
print("Validation TF-IDF Shape:", X_val_tfidf.shape)

Training TF-IDF Shape: (800, 28335)
Validation TF-IDF Shape: (200, 28335)

## And the Train a Classifier?

In [90]:
# Your code
# I looked up and I see that we can use Logistic Regression, Linear SVM, or Naive Bayes
# It suggested that Multinomial Naive Bayes is common for spam detection 

from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_tfidf, data_train['label'])
y_pred = model.predict(X_val_tfidf)

In [91]:
from sklearn.metrics import classification_report
print(classification_report(data_val['label'], y_pred))

              precision    recall  f1-score   support

           0       1.00      0.91      0.95       112
           1       0.90      1.00      0.95        88

    accuracy                           0.95       200
   macro avg       0.95      0.96      0.95       200
weighted avg       0.96      0.95      0.95       200

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [ ]:
# Your code

# So we did the TF-IDF already

In [92]:
# Bag of Words only 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

vectorizer = CountVectorizer()

X_train_bow = vectorizer.fit_transform(data_train['text'])
X_val_bow = vectorizer.transform(data_val['text'])

model = MultinomialNB()
model.fit(X_train_bow, data_train['label'])
y_pred = model.predict(X_val_bow)

from sklearn.metrics import classification_report
print(classification_report(data_val['label'], y_pred))

              precision    recall  f1-score   support

           0       1.00      0.95      0.97       112
           1       0.94      1.00      0.97        88

    accuracy                           0.97       200
   macro avg       0.97      0.97      0.97       200
weighted avg       0.97      0.97      0.97       200

In [93]:
# Now Bag of Words plus Extra Features 

from sklearn.feature_extraction.text import CountVectorizer
bow_vectorizer = CountVectorizer()

X_train_bow = bow_vectorizer.fit_transform(data_train['text'])
X_val_bow = bow_vectorizer.transform(data_val['text'])

In [94]:
X_train_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 77505 stored elements and shape (800, 28335)>

In [ ]:
extra_train = data_train[['money_mark', 'suspicious_words', 'text_len']]
extra_val = data_val[['money_mark', 'suspicious_words', 'text_len']]

In [ ]:
from scipy.sparse import hstack

X_train_bow_extra = hstack([X_train_bow, extra_train])
X_val_bow_extra = hstack([X_val_bow, extra_val])

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_bow_extra, data_train['label'])

y_pred = model.predict(X_val_bow_extra)

from sklearn.metrics import classification_report
print(classification_report(data_val['label'], y_pred))

              precision    recall  f1-score   support

           0       1.00      0.73      0.85       112
           1       0.75      1.00      0.85        88

    accuracy                           0.85       200
   macro avg       0.87      0.87      0.85       200
weighted avg       0.89      0.85      0.85       200

In [97]:
# Now TF-IDF with the extra features
from sklearn.feature_extraction.text import TfidfVectorizer

# Load vectorizer
vectorizer = TfidfVectorizer()

# Vectorize all dataset
X_train_tfidf = vectorizer.fit_transform(data_train['text'])
X_val_tfidf = vectorizer.transform(data_val['text'])

# Print shape of vectorized dataset
print("Training TF-IDF Shape:", X_train_tfidf.shape)
print("Validation TF-IDF Shape:", X_val_tfidf.shape)

# Extra Features
extra_train = data_train[['money_mark', 'suspicious_words', 'text_len']]
extra_val = data_val[['money_mark', 'suspicious_words', 'text_len']]

# Combine
X_train_tfidf_extra = hstack([X_train_tfidf, extra_train])
X_val_tfidf_extra = hstack([X_val_tfidf, extra_val])

# Train
model = MultinomialNB()
model.fit(X_train_tfidf_extra, data_train['label'])

# Predict
y_pred = model.predict(X_val_tfidf_extra)

# Evaluate
print(classification_report(data_val['label'], y_pred))

Training TF-IDF Shape: (800, 28335)
Validation TF-IDF Shape: (200, 28335)
              precision    recall  f1-score   support

           0       1.00      0.30      0.47       112
           1       0.53      1.00      0.69        88

    accuracy                           0.61       200
   macro avg       0.77      0.65      0.58       200
weighted avg       0.79      0.61      0.57       200

# Extra Task Conclusion

| Method | Accuracy |
|---|---|
| TF-IDF only | 95% |
| BoW only | 97% |
| BoW + extra features | 85% |
| TF-IDF + extra features | 61% |

* Among all tested methods, Bag of Words alone achieved the highest accuracy for spam classification, using Naive Bayes as the Classifier. 
* It is easy to think that adding more features could boost the performance, however, results showed that adding more actually did not necessarily mean better performance. 
* We can say that with all the data cleaning, the dataset is already extremely well separated by vocabulary alone. 
* Just an observation, using TF-IDF and extra features actually tanked the accuracy. 
* The added features (money mark, suspicious words, and text length) seemed to add more noise to the dataset.