In [22]:
from IPython.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

# Lab | Natural Language Processing
### SMS: SPAM or HAM

### Let's prepare the environment

In [23]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import TfidfVectorizer

- Read Data for the Fraudulent Email Kaggle Challenge
- Reduce the training set to speead up development.

In [24]:
## Read Data for the Fraudulent Email Kaggle Challenge
data = pd.read_csv("../data/kg_train.csv",encoding='latin-1')

# Reduce the training set to speed up development. 
# Modify for final system
data = data.head(1000)
print(data.shape)
data.fillna("",inplace=True)

(1000, 2)

                                                  text  label
0    DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...      1
1                                             Will do.      0
2    Nora--Cheryl has emailed dozens of memos about...      0
3    Dear Sir=2FMadam=2C I know that this proposal ...      1
4                                                  fyi      0
..                                                 ...    ...
995  So what's the latest? It sounds contradictory ...      0
996  TRANSFER OF 36,759,000.00 MILLION POUNDS TO YO...      1
997  Barb I will call to explain. Are you back in t...      0
998    Yang on travelNot free tonite.May work tomorrow      0
999  sbwhoeopSunday February 21 2010 7:42 PMHShaunH...      0

[1000 rows x 2 columns]

### Let's divide the training and test set into two partitions

In [25]:
from sklearn.model_selection import train_test_split
X = data["text"]     # email content
y = data["label"]    # 0 = ham, 1 = spam
X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=0.2,      # 80% train, 20% test
    random_state=42,    # reproducibility
    stratify=y          # keeps class balance
)

print(X_train.head())
print(X_val.head())

442    Dear=2C Good day hope fine=2Cdear am writting ...
962    FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...
971                                             Will do.
190    FROM THE DESK OF DR.ADAMU  ISMALERAUDITING AND...
551    Dear Friend, My name is LOI C.ESTRADA,The wife...
Name: text, dtype: str
222    STRICTLY PERSONALPermit me to introduce myself...
824    Dear Nancy--I very much want to meet and we've...
505    REQUEST FOR BUSINESS PARTNERSHIPI am PATRICK A...
165    Soneri Bank LimitedSilver Jubilee Center=2CBri...
832    Dear Partner,I am a Fund Manager with Fidelity...
Name: text, dtype: str

In [26]:
#####

## Data Preprocessing

In [27]:
import string
from nltk.corpus import stopwords
print(string.punctuation)
print(stopwords.words("english")[100:110])
from nltk.stem.snowball import SnowballStemmer
snowball = SnowballStemmer('english')

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
['needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on']

## Now, we have to clean the html code removing words

- First we remove inline JavaScript/CSS
- Then we remove html comments. This has to be done before removing regular tags since comments can contain '>' characters
- Next we can remove the remaining tags

In [28]:
import re

def clean_html(text):
    text = str(text)
    # remove inline JavaScript
    text = re.sub(r'<script.*?>.*?</script>', ' ', text, flags=re.DOTALL | re.IGNORECASE)
    
    # remove inline CSS
    text = re.sub(r'<style.*?>.*?</style>', ' ', text, flags=re.DOTALL | re.IGNORECASE)

    # remove html comments
    text = re.sub(r'<!--.*?-->', ' ', text, flags=re.DOTALL)

    # remove the remaining tags
    text = re.sub(r'<[^>]+>', ' ', text)

    return text

- Remove all the special characters
    
- Remove numbers
    
- Remove all single characters
 
- Remove single characters from the start

- Substitute multiple spaces with single space

- Remove prefixed 'b'

- Convert to Lowercase

Cleanup order is important: **structure → normalization → cleaning → refinement → formatting**

- If **lowercasing is done too late**, `"A"` may not match `[a-z]`, and some regex patterns may miss uppercase letters. It is better to normalize early.
- If **removing the prefixed `b` is done too late**, `b'Hello'` can become `b Hello` after removing special characters, so `^b` removal may not behave as expected. Structural cleanup should come first.
- If **spaces are collapsed too early**, later transformations such as removing the prefixed `b` can introduce new spacing issues again.
- If **special characters are removed before lowercasing**, it can still work, but best practice is to lowercase first and then clean.

Recommended order:
1. Remove prefixed `b`
2. Convert to lowercase
3. Remove special characters
4. Remove numbers
5. Remove single characters
6. Remove single characters from the start
7. Substitute multiple spaces with a single space

In [29]:
def clean_text(text):
    text = str(text)
    # Remove prefixed 'b'
    text = re.sub(r"^b\s+", "", text)
    
    # Convert to lowercase
    text = text.lower()
    
    # Remove numbers
    text = re.sub(r'\d+', ' ', text)
    
    # Remove special characters
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)
    
    # Remove all single characters
    text = re.sub(r'\b[a-zA-Z]\b', ' ', text)
    
    # Remove single characters from the start
    text = re.sub(r'^\s*[a-zA-Z]\s+', ' ', text)
    
    # Substitute multiple spaces with single space
    text = re.sub(r'\s+', ' ', text).strip()

    return text

data["preprocessed_text"] = data["text"].apply(clean_html).apply(clean_text)

data[["text", "preprocessed_text"]].head()

,text,preprocessed_text
0,"DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...",dear sir strictly private business proposal am...
1,Will do.,will do
2,Nora--Cheryl has emailed dozens of memos about...,nora cheryl has emailed dozens of memos about ...
3,Dear Sir=2FMadam=2C I know that this proposal ...,dear sir fmadam know that this proposal might ...
4,fyi,fyi

## Now let's work on removing stopwords
Remove the stopwords.

In [30]:
stop_words = set(stopwords.words("english"))
data["tokens"] = data["preprocessed_text"].str.split()
data["tokens_no_stop"] = data["tokens"].apply(
    lambda words: [word for word in words if word not in stop_words]
)

## Tame Your Text with Lemmatization
Break sentences into words, then use lemmatization to reduce them to their base form (e.g., "running" becomes "run"). See how this creates cleaner data for analysis!

In [31]:
from nltk.stem import WordNetLemmatizer

# nltk.download('wordnet')
# nltk.download('omw-1.4')

lemmatizer = WordNetLemmatizer()
data["tokens_lemma"] = data["tokens_no_stop"].apply(
    lambda words: [lemmatizer.lemmatize(word) for word in words]
)

data["preprocessed_text"] = data["tokens_lemma"].apply(lambda words: " ".join(words))
data[["text", "preprocessed_text"]].head()

,text,preprocessed_text
0,"DEAR SIR, STRICTLY A PRIVATE BUSINESS PROPOSAL...",dear sir strictly private business proposal mi...
1,Will do.,
2,Nora--Cheryl has emailed dozens of memos about...,nora cheryl emailed dozen memo haiti weekend p...
3,Dear Sir=2FMadam=2C I know that this proposal ...,dear sir fmadam know proposal might surprise e...
4,fyi,fyi

## Bag Of Words
Let's get the 10 top words in ham and spam messages (**EXPLORATORY DATA ANALYSIS**)

In [32]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np


ham = data[data["label"] == 0]
spam = data[data["label"] == 1]

# Rebuild train/validation DataFrames
data_train = X_train.to_frame(name="preprocessed_text")
data_train["label"] = y_train.values

data_val = X_val.to_frame(name="preprocessed_text")
data_val["label"] = y_val.values
print(data_train.head())
print(data_val.head())

bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(data_train["preprocessed_text"])
X_val_bow = bow_vectorizer.transform(data_val["preprocessed_text"])

# Get vocabulary (words)
words = bow_vectorizer.get_feature_names_out()

# Convert labels to numpy
labels = data_train["label"].to_numpy()

# Ham = 0, Spam = 1
ham_counts = np.array(X_train_bow[labels == 0].sum(axis=0)).flatten()
spam_counts = np.array(X_train_bow[labels == 1].sum(axis=0)).flatten()

# Get top 10 words
ham_top_idx = ham_counts.argsort()[-10:][::-1]
spam_top_idx = spam_counts.argsort()[-10:][::-1]

print("Top 10 HAM words:")
for i in ham_top_idx:
    print(words[i], ":", ham_counts[i])

print("\nTop 10 SPAM words:")
for i in spam_top_idx:
    print(words[i], ":", spam_counts[i])

                                     preprocessed_text  label
442  Dear=2C Good day hope fine=2Cdear am writting ...      1
962  FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...      1
971                                           Will do.      0
190  FROM THE DESK OF DR.ADAMU  ISMALERAUDITING AND...      1
551  Dear Friend, My name is LOI C.ESTRADA,The wife...      1
                                     preprocessed_text  label
222  STRICTLY PERSONALPermit me to introduce myself...      1
824  Dear Nancy--I very much want to meet and we've...      0
505  REQUEST FOR BUSINESS PARTNERSHIPI am PATRICK A...      1
165  Soneri Bank LimitedSilver Jubilee Center=2CBri...      1
832  Dear Partner,I am a Fund Manager with Fidelity...      1
Top 10 HAM words:
the : 1595
to : 930
and : 733
of : 687
in : 548
that : 378
for : 337
is : 334
on : 289
you : 256

Top 10 SPAM words:
the : 5611
to : 4350
of : 3955
and : 3128
in : 2595
you : 2564
this : 2076
my : 1674
your : 1668
2e : 1595

## Extra features

In [33]:
print(data_train.columns)

Index(['preprocessed_text', 'label'], dtype='str')

In [34]:
# We add to the original dataframe two additional indicators (money symbols and suspicious words).
money_simbol_list = "|".join(["euro","dollar","pound","€",r"\$"])
suspicious_words = "|".join(["free","cheap","sex","money","account","bank","fund","transfer","transaction","win","deposit","password"])

data_train['money_mark'] = data_train['preprocessed_text'].str.contains(money_simbol_list)*1
data_train['suspicious_words'] = data_train['preprocessed_text'].str.contains(suspicious_words)*1
data_train['text_len'] = data_train['preprocessed_text'].apply(lambda x: len(x)) 

data_val['money_mark'] = data_val['preprocessed_text'].str.contains(money_simbol_list)*1
data_val['suspicious_words'] = data_val['preprocessed_text'].str.contains(suspicious_words)*1
data_val['text_len'] = data_val['preprocessed_text'].apply(lambda x: len(x)) 

data_train.head()

,preprocessed_text,label,money_mark,suspicious_words,text_len
442,Dear=2C Good day hope fine=2Cdear am writting ...,1,0,1,1609
962,FROM MR HENRY KABORETHE CHIEF AUDITOR INCHARGE...,1,1,1,3123
971,Will do.,0,0,0,8
190,FROM THE DESK OF DR.ADAMU ISMALERAUDITING AND...,1,1,1,530
551,"Dear Friend, My name is LOI C.ESTRADA,The wife...",1,1,1,2126

## How would work the Bag of Words with Count Vectorizer concept?

In [35]:
from sklearn.feature_extraction.text import CountVectorizer
from scipy.sparse import hstack

bow_vectorizer = CountVectorizer(
    token_pattern=r'\b[a-zA-Z]{3,}\b',  # only alphabetic words, at least 3 letters
    max_features=5000                   # optional: keep top 5000 words
)

X_train_bow = bow_vectorizer.fit_transform(data_train["preprocessed_text"])
X_val_bow = bow_vectorizer.transform(data_val["preprocessed_text"])

extra_train = data_train[["money_mark", "suspicious_words", "text_len"]]
extra_val = data_val[["money_mark", "suspicious_words", "text_len"]]

X_train_final = hstack([X_train_bow, extra_train])
X_val_final = hstack([X_val_bow, extra_val])

print("BoW shape:", X_train_bow.shape)
print("Extra features shape:", extra_train.shape)
print("Final shape:", X_train_final.shape)

BoW shape: (800, 5000)
Extra features shape: (800, 3)
Final shape: (800, 5003)

Bag of Words converted the training text into a numerical matrix with 15,425 word features. After adding the three handcrafted features (money_mark, suspicious_words, and text_len), the final training matrix had 15,428 features.

## TF-IDF

- Load the vectorizer

- Vectorize all dataset

- print the shape of the vetorized dataset

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(
    token_pattern=r'\b[a-zA-Z]{3,}\b'   # optional (cleaner words)
)
X_train_tfidf = tfidf_vectorizer.fit_transform(data_train["preprocessed_text"])
X_val_tfidf = tfidf_vectorizer.transform(data_val["preprocessed_text"])
print("TF-IDF train shape:", X_train_tfidf.shape)
print("TF-IDF val shape:", X_val_tfidf.shape)

extra_train = data_train[["money_mark", "suspicious_words", "text_len"]]
extra_val = data_val[["money_mark", "suspicious_words", "text_len"]]

X_train_final = hstack([X_train_tfidf, extra_train])
X_val_final = hstack([X_val_tfidf, extra_val])

print("Final TF-IDF shape:", X_train_final.shape)

TF-IDF train shape: (800, 14993)
TF-IDF val shape: (200, 14993)
Final TF-IDF shape: (800, 14996)

In [37]:
print(extra_train.dtypes)

money_mark          int64
suspicious_words    int64
text_len            int64
dtype: object

## And the Train a Classifier?

In [38]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Train classifier
clf = LogisticRegression(max_iter=1000)
clf.fit(X_train_final, y_train)

# Predict on validation set
y_pred = clf.predict(X_val_final)

# Evaluate
print("Accuracy:", accuracy_score(y_val, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_val, y_pred))
print("\nClassification Report:")
print(classification_report(y_val, y_pred))

Accuracy: 0.955

Confusion Matrix:
[[111   1]
 [  8  80]]

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.99      0.96       112
           1       0.99      0.91      0.95        88

    accuracy                           0.95       200
   macro avg       0.96      0.95      0.95       200
weighted avg       0.96      0.95      0.95       200

111 correct ham predictions
80 correct spam predictions
1 false alarm (ham → spam)
8 missed spam emails means 8 spam emails classified as ham.

The model achieved 95.5% accuracy on the validation set. It performs very well in identifying both ham and spam messages. However, the recall for spam (0.91) indicates that some fraudulent emails are still misclassified as legitimate, which could be critical in real-world applications.

### Extra Task - Implement a SPAM/HAM classifier

https://www.kaggle.com/t/b384e34013d54d238490103bc3c360ce

The classifier can not be changed!!! It must be the MultinimialNB with default parameters!

Your task is to **find the most relevant features**.

For example, you can test the following options and check which of them performs better:
- Using "Bag of Words" only
- Using "TF-IDF" only
- Bag of Words + extra flags (money_mark, suspicious_words, text_len)
- TF-IDF + extra flags


You can work with teams of two persons (recommended).

In [39]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from scipy.sparse import hstack
import pandas as pd

results = []

# target
y_train_nb = y_train
y_val_nb = y_val

# extra features
extra_train = data_train[["money_mark", "suspicious_words", "text_len"]]
extra_val = data_val[["money_mark", "suspicious_words", "text_len"]]

# 1) Bag of Words only
bow_vectorizer = CountVectorizer(token_pattern=r'\b[a-zA-Z]{3,}\b')
X_train_bow = bow_vectorizer.fit_transform(data_train["preprocessed_text"])
X_val_bow = bow_vectorizer.transform(data_val["preprocessed_text"])

model_bow = MultinomialNB()
model_bow.fit(X_train_bow, y_train_nb)
y_pred_bow = model_bow.predict(X_val_bow)

results.append({
    "Features": "Bag of Words only",
    "Accuracy": accuracy_score(y_val_nb, y_pred_bow)
})

print("Bag of Words only")
print("Accuracy:", accuracy_score(y_val_nb, y_pred_bow))
print(confusion_matrix(y_val_nb, y_pred_bow))
print(classification_report(y_val_nb, y_pred_bow))


# 2) TF-IDF only
tfidf_vectorizer = TfidfVectorizer(token_pattern=r'\b[a-zA-Z]{3,}\b')
X_train_tfidf = tfidf_vectorizer.fit_transform(data_train["preprocessed_text"])
X_val_tfidf = tfidf_vectorizer.transform(data_val["preprocessed_text"])

model_tfidf = MultinomialNB()
model_tfidf.fit(X_train_tfidf, y_train_nb)
y_pred_tfidf = model_tfidf.predict(X_val_tfidf)

results.append({
    "Features": "TF-IDF only",
    "Accuracy": accuracy_score(y_val_nb, y_pred_tfidf)
})

print("\nTF-IDF only")
print("Accuracy:", accuracy_score(y_val_nb, y_pred_tfidf))
print(confusion_matrix(y_val_nb, y_pred_tfidf))
print(classification_report(y_val_nb, y_pred_tfidf))


# 3) Bag of Words + extra flags
X_train_bow_extra = hstack([X_train_bow, extra_train])
X_val_bow_extra = hstack([X_val_bow, extra_val])

model_bow_extra = MultinomialNB()
model_bow_extra.fit(X_train_bow_extra, y_train_nb)
y_pred_bow_extra = model_bow_extra.predict(X_val_bow_extra)

results.append({
    "Features": "Bag of Words + extra flags",
    "Accuracy": accuracy_score(y_val_nb, y_pred_bow_extra)
})

print("\nBag of Words + extra flags")
print("Accuracy:", accuracy_score(y_val_nb, y_pred_bow_extra))
print(confusion_matrix(y_val_nb, y_pred_bow_extra))
print(classification_report(y_val_nb, y_pred_bow_extra))


# 4) TF-IDF + extra flags
X_train_tfidf_extra = hstack([X_train_tfidf, extra_train])
X_val_tfidf_extra = hstack([X_val_tfidf, extra_val])

model_tfidf_extra = MultinomialNB()
model_tfidf_extra.fit(X_train_tfidf_extra, y_train_nb)
y_pred_tfidf_extra = model_tfidf_extra.predict(X_val_tfidf_extra)

results.append({
    "Features": "TF-IDF + extra flags",
    "Accuracy": accuracy_score(y_val_nb, y_pred_tfidf_extra)
})

print("\nTF-IDF + extra flags")
print("Accuracy:", accuracy_score(y_val_nb, y_pred_tfidf_extra))
print(confusion_matrix(y_val_nb, y_pred_tfidf_extra))
print(classification_report(y_val_nb, y_pred_tfidf_extra))


# Summary table
results_df = pd.DataFrame(results).sort_values(by="Accuracy", ascending=False)
print("\nComparison of feature sets:")
print(results_df)

Bag of Words only
Accuracy: 0.945
[[101  11]
 [  0  88]]
              precision    recall  f1-score   support

           0       1.00      0.90      0.95       112
           1       0.89      1.00      0.94        88

    accuracy                           0.94       200
   macro avg       0.94      0.95      0.94       200
weighted avg       0.95      0.94      0.95       200


TF-IDF only
Accuracy: 0.91
[[94 18]
 [ 0 88]]
              precision    recall  f1-score   support

           0       1.00      0.84      0.91       112
           1       0.83      1.00      0.91        88

    accuracy                           0.91       200
   macro avg       0.92      0.92      0.91       200
weighted avg       0.93      0.91      0.91       200


Bag of Words + extra flags
Accuracy: 0.905
[[93 19]
 [ 0 88]]
              precision    recall  f1-score   support

           0       1.00      0.83      0.91       112
           1       0.82      1.00      0.90        88

    accuracy                           0.91       200
   macro avg       0.91      0.92      0.90       200
weighted avg       0.92      0.91      0.91       200


TF-IDF + extra flags
Accuracy: 0.715
[[55 57]
 [ 0 88]]
              precision    recall  f1-score   support

           0       1.00      0.49      0.66       112
           1       0.61      1.00      0.76        88

    accuracy                           0.71       200
   macro avg       0.80      0.75      0.71       200
weighted avg       0.83      0.71      0.70       200


Comparison of feature sets:
                     Features  Accuracy
0           Bag of Words only     0.945
1                 TF-IDF only     0.910
2  Bag of Words + extra flags     0.905
3        TF-IDF + extra flags     0.715

I evaluated four feature configurations using the MultinomialNB classifier with default parameters:

1. Bag of Words only
2. TF-IDF only
3. Bag of Words + extra features
4. TF-IDF + extra features

The best performance was achieved using the Bag of Words representation, with an accuracy of 94.5%. This configuration provided a strong balance between precision and recall and correctly identified all spam messages.

TF-IDF performed worse (91% accuracy), likely because it downweights frequently occurring words that are actually important for spam detection, such as "free" and "money".

Adding extra handcrafted features (money_mark, suspicious_words, text_len) did not improve performance. In fact, it slightly reduced accuracy when combined with Bag of Words and significantly degraded performance when combined with TF-IDF.

Overall, the results show that Bag of Words is the most effective feature representation for this task when using MultinomialNB, and additional features are not necessary.